### ISSUE TITLE
Running with Multiple HLA allele 

### ISSUE THREAD

**Issue by pankajvats** [griffithlab/pVAC-Seq#109]
pvacseq version2.0.0
pvacseq run example.vcf test  /home/softwares/NetMHC HLA-A01:01,HLA-A02:01,HLA-A02:02,HLA-A02:03,HLA-A02:06,HLA-A02:11,HLA-A02:12,HLA-A02:16 9 Temp/

the output:
**Temp/test_filtered.tsv** for only the HLA-A02:16

suggestion:
Also for peptide length in frame shifts insertion/deletion should go till it hit the stop codon.

**Comment by susannasiebert** [comment]
Thanks for making us aware of this bug. We are currently working on a hotfix. 

As far as peptide lengths for frameshifts, the mutant contains the full downstream sequence and the peptide length is only applied to the wildtype. Have a look at the test_21.fa in your output folder to see the peptide sequences that get submitted to NetMHC. Does that answer your question?

**Comment by pankajvats** [comment]
Thanks for prompt reply!!
 
does the frameshits mutant peptide length goes till it hit the stop codon ?
are you also considering the fusion for peptide prediction ?

**Comment by pankajvats** [comment]
frameshifts "typo"

**Comment by susannasiebert** [comment]
For frameshifts we use the VEP Downstream plugin and we include the full peptide sequence it returns. Please see here for documentation on this plugin: http://www.ensembl.info/ecode/downstream/. Whether or not the peptide goes all the way to the stop codon is a question you would need to ask the developers of the plugin.

We are planning on incorporating fusions in the future although we don't have a deadline for it at this point.

**Comment by pankajvats** [comment]
great thanks !!

**Comment by susannasiebert** [comment]
We made a new version of pvacseq to fix the bug you encountered. Please run `pip install pvacseq --upgrade` to upgrade to the newest version (2.0.3).

**Comment by pankajvats** [comment]
Thanks will try running the new version.

**Comment by pankajvats** [comment]
pvacseq complains about vcf if it contain normal tumor samples in it.

**Comment by susannasiebert** [comment]
pvacseq expects the VCF to only contain one sample. VCFs with multiple samples are currently not supported.

**Comment by pankajvats** [comment]
ok, i tried feeding varscan somatic vcf file direct to pvaseq

**Comment by susannasiebert** [comment]
You will need to split the VCF by sample and annotate each VCF with VEP before processing it with pvacseq. The VCF needs to be VEP-annotated as described here: https://github.com/griffithlab/pVAC-Seq#vep

**Comment by pankajvats** [comment]
great thanks!!

**Comment by susannasiebert** [comment]
I believe the original problem in this issue has been resolved. Please open a new issue if you encounter any future problems.
