### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by strixeh** [griffithlab/pVAC-Seq#113]
Hey again :)!

I used `example_GRCh38.vcf` from the VEP tutorial to run pvacseq 3.0.0. First, i ran `perl variant_effect_predictor.pl --no_progress --species human --cache -i /home/strix/ensembl-tools-release-84/scripts/variant_effect_predictor/example_GRCh38.vcf --format vcf -o /home/strix/pvacseq/input/test.vcf --vcf --symbol --terms SO --plugin Downstream --plugin Wildtype --dir_plugins /home/strix/anaconda3/lib/python3.5/site-packages/pvacseq/VEP_plugins` to create my annotated test.vcf file. 

This test.vcf file runs fine with `pvacseq run /home/strix/pvacseq/input/test.vcf test HLA-A*01:01 9 NetMHC /home/strix/pvacseq/output/test`.

However, when i remove all data rows except the first in `example_GRCh38.vcf`, run the same VEP and pvacseq call as above, this gives me an error when executing pvacseq:

```
Converting VCF to TSV
Completed
Generating Variant Peptide FASTA File
Completed
Generating FASTA Key File
Completed
Running IEDB on Allele HLA-A*01:01 and Epitope Length 9 with Method NetMHC
Traceback (most recent call last):
  File "/home/strix/anaconda3/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/home/strix/anaconda3/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 86, in main
    args[0].func.main(args[1])
  File "/home/strix/anaconda3/lib/python3.5/site-packages/pvacseq/lib/main.py", line 146, in main
    with open(split_iedb_output_files[0]) as split_iedb_out_file:
IndexError: list index out of range
```

If I keep about 20 rows in my input vcf file, then it all works just fine. But one or two rows, nope. Any ideas?

Thanks,
Nils

**Comment by susannasiebert** [comment]
Hm, this is interesting. This code is part of some processing we do behind the scenes to split up large input files. It's a bit puzzling why this would fail on small input files though. Is it maybe the case that the one/two variants you left in the vcf are getting filtered out? This would happen if none of them are missense, inframe indels, or frameshifts. You can also check your tsv file in your output directory and if it doesn't contain any entries then all of them got filtered out during conversion for the above reason.

Either way we will need to add some exit clause to stop processing if the vcf doesn't contain any entries of the expected variant type.

**Comment by strixeh** [comment]
Hi! You are completely right. The entries I had was actually synonymous mutations. Sorry for the confusion, should have checked this prior to sending you a ticket. 

Thanks,
Nils

**Comment by susannasiebert** [comment]
Glad we got it figured out. I made a pull request to add a check that the fasta created by pvacseq has entries before continuing processing. This should prevent this error in the future. This fix will be part of the upcoming hotfix release.
