### ISSUE TITLE
NetMHC allele not valid

### ISSUE THREAD

**Issue by jonathancmw** [griffithlab/pVAC-Seq#12]
Hi,
I have installed netMHC-4.0 and it is working by itself using when I try with test data. However, when I try to carry out the test using pVAC-Seq and the example data, I get the following:

```
$ ./pVAC-Seq.pl  --input-file test_data/annotated_variants.tsv --sample-name Test --netmhc-path netMHC-4.0/netMHC --allele HLA-A0302 --varpeptide-length 21 --epitope-length 9 --output-dir my_test_data/

#GENERATING VARIANT PEPTIDE FASTA FILE: COMPLETED
#GENERATING FASTA KEY FILE: COMPLETED NetMHC allele not valid. Please check usingnetMHC-4.0/netMHC-A COMPLETED
#PARSING NETMHC OUTPUT:File my_test_data//Test.-A.9.netmhc.xls doesn't exist -- fatal.
COMPLETED
#RUNNING BINDING FILTERS: Could not open file 'my_test_data//Test.-A.9.netmhc.parsed' No such file or directory at bin/BindingFilter.pl line 96, <FOF> line 1.
Could not open file 'my_test_data//Test.-A.9.netmhc.parsed' No such file or directory at bin/BindingFilter.pl line 96, <FOF> line 1.
COMPLETED

DONE: pVac-Seq.pl has completed. File Test_filtered.xls contains list of binding-filtered putative neoantigens.
```
I have tried this with --allele set as HLA-A0302 and HLA-A03:02 but no luck. After doing 'netMHC-4.0/netMHC -a' (which seems fine), I'm not sure what is going wrong here.

Any help would be greatly appreciated

Jonathan (CSHL advanced sequencing 2015 alumnus!)

**Comment by malachig** [comment]
Hi @jonathancmw .  Thanks for trying this out.  In case Jasreet didn't see this notification, @jhundal have you seen an error like this this?

**Comment by jhundal** [comment]
Hi @jonathancmw, thanks for trying out pVAC-Seq. We haven't yet tested this out on the newly released version of NetMHC- version 4, but from your test command, it seems like you are trying to run it on allele HLA-A0302, whereas the current listing of allele names from the NetMHC website does not show A0302 as one of the compatible alleles.
http://www.cbs.dtu.dk/services/NetMHC/MHC_allele_names.txt
Do you see this allele listed when you do 'netMHC-4.0/netMHC -a'?

BTW, HLA-A0301 seems to be supported by NetMHC, so maybe you could test it out with that instead.

**Comment by personalis** [comment]
Note that the -A argument doesn't exist anymore in NetMHC v4.0.  It has been replaced by '-listMHC'.  This is one reason why pVAC-Seq doesn't currently work with NetMHC v4.0.

**Comment by jhundal** [comment]
Thank you @personalis for that info. We are hoping to release a new version of pVAC-Seq with compatibility for NetMHC v4.0.

**Comment by personalis** [comment]
FYI, here is the full set of changes I had to make to get it to work with NetMHC v4.0:
`-my $netmhc_a = `$netmhc_path -A`;
+#JH: netMHC v4.0 uses 'listMHC' rather than '-A' to get the list of known HLA types
+my $netmhc_a = `$netmhc_path -listMHC -tdir /tmp`;
 my @allele_arr = split("\n", $netmhc_a);
 
 @allele = split(/,/,join(',',@allele));
@@ -105,6 +106,8 @@ my @allele_arr = split("\n", $netmhc_a);
 
 
 ### Run NETMHC allele-length combinations ###
+### JH: have to specify temp folder for NetMHC so it doesn't try to write to its install folder (!)
+### JH: Argument '-x outfile' changed to '-xls -xlsfile outfile' in NetMHC v4.0
 foreach my $epl (@epitope_len)
 {
        foreach my $a (@allele)
@@ -112,8 +115,8 @@ foreach my $epl (@epitope_len)
                if (grep {$_ eq $a} @allele_arr ) {
                        my $net_out = $sample_name.'.'.$a.'.'.$epl.'.netmhc.xls';
                        print "\n#RUNNING NETMHC ON ALLELE $a AND EPITOPE LENGTH $epl\n";
-                       my $netmhc_cmd = '$netmhc_path -a $a -l $epl $output_dir/$fasta_file -x $output_dir/$net_out';
-                       my $tmp = `$netmhc_path -a $a -l $epl $output_dir/$fasta_file -x $output_dir/$net_out`;
+                       my $netmhc_cmd = '$netmhc_path -a $a -l $epl $output_dir/$fasta_file -xls -xlsfile $output_dir/$net_out -tdir /tmp';
+                       my $tmp = `$netmhc_path -a $a -l $epl $output_dir/$fasta_file -xls -xlsfile $output_dir/$net_out -tdir /tmp`;
 
                }       
                else`

**Comment by personalis** [comment]
whoa, sorry for the messed up formatting.  I'll try to submit a pull request instead...

**Comment by personalis** [comment]
I sent the pull request.  Not for you to merge directly, just so you can see what I had to modify for NetMHC v4.0.

**Comment by amillerc** [comment]
Thank you @personalis for that fix. However, when I use this the Parse NETMHC results section turns up an empty file. Is there an additional change that needs to be made to the my$parse_cmd lines or surrounding code? 

Thanks!

**Comment by jhundal** [comment]
Hi @amillerc 
The output format for NetMHC v4.0 has changed, and the code will need some refactoring to incorporate the changes. We will soon be releasing newer version of pVAC-Seq compatible with NetMHC-4.0.

**Comment by malachig** [comment]
@amillerc, @personalis, and @jonathancmw .  Thanks for your interest in pVac-Seq.  We are definitely keen to take advantage of some of the new features of NetMHC v.4.0.  We will try to get that update in place asap.

**Comment by xigyou** [comment]
It's not valid too.

[youmingcong@bit-smt:/BIC/ymc/Neo/pVAC-Seq-1.0.0-beta]$ 
./pVAC-Seq.pl  --input-file ./test_data/annotated_variants.tsv --sample-name Test1 --netmhc-path /BIC/ymc/Neo/netMHC-4.0/netMHC --allele HLA-A29:02 --varpeptide-length 21 --epitope-length 9 --output-dir ./Test1

#GENERATING VARIANT PEPTIDE FASTA FILE: COMPLETED
#GENERATING FASTA KEY FILE: COMPLETEDNetMHC allele not valid. Please check using/BIC/ymc/Neo/netMHC-4.0/netMHC-ACOMPLETED
#PARSING NETMHC OUTPUT:File ./Test1/Test1.HLA-A29:02.9.netmhc.xls doesn't exist -- fatal.
COMPLETED
#RUNNING BINDING FILTERS: Could not open file './Test1/Test1.HLA-A29:02.9.netmhc.parsed' No such file or directory at bin/BindingFilter.pl line 96, <FOF> line 1.
Could not open file './Test1/Test1.HLA-A29:02.9.netmhc.parsed' No such file or directory at bin/BindingFilter.pl line 96, <FOF> line 1.
COMPLETED

DONE: pVac-Seq.pl has completed. File Test1_filtered.xls contains list of binding-filtered putative neoantigens.
We recommend appending coverage information and running bin/CoverageFilers.pl to filter based on sequencing coverage information as well.

waiting udate.

**Comment by strixeh** [comment]
Hi all,

As @amillerc pointed out, I also get a 0 b file when i try to use netMHC from the test folder: `../netMHC -a HLA-A02:01 test.fsa > test.fsa.myout`

Additionally, i got an error regarding that i needed parentheses around the call for print on line 115 in netMHC. As I understand, this is a problem when going from python2 to python3...? My line 115 now reads `print ("### Alleles with ANN predictors:")`. I am not sure if this is related to my 0 b file output problem or not... 

Any ideas?

Thanks,
Nils

**Comment by susannasiebert** [comment]
Nils, are you using NetMHC 3.4 or 4.0?

My guess is that when it encountered the print error on line 115 it didn't actually write anything to the output file. Did you still get a 0b output file once you added the parentheses?

**Comment by strixeh** [comment]
Hi, I am using NetMHC 3.4. I still get the 0b file after added the parentheses. I have had some help during this morning from a bioinformatician from our Core Facility. We were able to change the NetMHC.py script enough to at least have a output file containing a header. We havent finished working yet, but he says NetMHC is written for Python2, and that this creates a problem because my environment is trying to call Python3. Would it be easier for us to try using NetMHC 4.0?

Thanks,
Nils

**Comment by susannasiebert** [comment]
This is really a problem with NetMHC and not with pvacseq so I would suggest contacting them to get assistance in running/modifying their software. If you are running NetMHC independently you could try using conda to emulate a python 2.7 environment, or simply go into a terminal that doesn't have your conda python 3.5 environment activated. This won't fix the problem with gawk though. I'm not too familiar with the OSX core function (we program on Linux) but maybe there is something equivalent that you could use to replace the gawk call.

**Comment by susannasiebert** [comment]
I also meant to say that the NetMHC 4.0 output won't be compatible with pvacseq as the output format is different from 3.4.

If you can get NetMHC3.4 to run on a python 2.7 environment like described above you can then execute the subsequent pvacseq steps independently on the NetMCH output once you are back in a python 3.5 environment.

**Comment by strixeh** [comment]
Yes, I have already contacted them but they have not responded yet. My idea was to contact you since pvacseq needs a functioning NetMHC, but I completely understand all cant be covered by you guys! Thanks again for the good work and the help!

**Comment by susannasiebert** [comment]
Depending on what the timeline is on your side of things, we're currently working on a new release that wouldn't depend on a local install of NetMHC 3.4. We're hoping to release it next week.

**Comment by strixeh** [comment]
@susannasiebert That is awesome. Looking forward to that release!

**Comment by jasonwalker80** [comment]
pvacseq 3.0.0 was released on Friday.
