### ISSUE TITLE
Add NetMHCstabpan predictions to the end of the pVAC-Seq workflow.

### ISSUE THREAD

**Issue by jasonwalker80** [griffithlab/pVAC-Seq#138]
This is similar to #74

**Comment by agraubert** [comment]
I've only given it a brief look so far, but the [NetMHCstab server](http://www.cbs.dtu.dk/services/NetMHCstab-1.0/) looks like it only supports a very small set of HLA alleles (only a handful of subtypes of HLA-A and B).  Should pvacseq just skip over sending peptides from unsupported alleles?

**Comment by susannasiebert** [comment]
I think that would be the way to go.

**Comment by jhundal** [comment]
@agraubert: We could look at [NetMHCstabpan](http://www.cbs.dtu.dk/services/NetMHCstabpan/) instead. It supports more alleles than NetMHCStab.

**Comment by agraubert** [comment]
Alright, that looks like it should work.  I'll have the script work with that instead
