### ISSUE TITLE
Bugs in CoverageFilters

### ISSUE THREAD

**Issue by Irrationone** [griffithlab/pVAC-Seq#14]
Hello,

Thanks for this tool! I noticed a few bugs in CoverageFilters.pl:

- `--expn-val` is an unrecognized argument -- it's not read by the `GetOptions` call
- `$fpkm` appears to be doubling up on the purpose of `$expn_val`. The documented option is `--expn-val`, but the script actually accepts the option `--fpkm` instead (and defines both variables, which leads to the third issue below). 
- The expression filter is doing nothing at the moment, since the conditional `$expn_val >= $fpkm` should read `$fpkmval >= $expn_val`. The first version results in the conditional always comparing two constants with each other, which are both 1 by default.

**Comment by jhundal** [comment]
@Irrationone Thanks for using pVAC-Seq, and bringing this bug to our notice. We have added in the fix, along with tests.
