### ISSUE TITLE
Explore command line tab completion

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVAC-Seq#145]
This looks promising: https://pypi.python.org/pypi/argcomplete/1.4.1

**Comment by susannasiebert** [comment]
I did some more digging into [argcomplete](http://argcomplete.readthedocs.io/en/latest/index.html). If I'm understanding this correctly there would be some/a lot of manipulation by the pVAC-Seq user involved in order to turn on tab-completion on their system. For users with bash 4.2+ they need to run the script `activate-global-python-argcomplete` which will try to install the file `bash_completion.d/python-argcomplete.sh` into an appropriate location on the user's system. The user will then need to source this file into their ~/.bashrc. For lower versioned bash systems the user will need to source every individual script in their ~/.bashrc. I haven't been able to find information on how that would be achieved for packaged code. 

I haven't found any other module that works better so I propose that we close this issue as `wontfix`.

**Comment by malachig** [comment]
+1. Probably not worth the hassle and increased config complexity for the end user.
