### ISSUE TITLE
pvacseq 3.0.4 still throws the same error for indels !!

### ISSUE THREAD

**Issue by pankajvats** [griffithlab/pVAC-Seq#155]
Error:
pvacseq run pvaseq_test_error.vcf tt HLA-A*02:01 9,10 NetMHC Neo/ -l 21 --top-result-per-mutation
Converting VCF to TSV
Completed
Generating Variant Peptide FASTA File
Traceback (most recent call last):
File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/bin/pvacseq", line 11, in
sys.exit(main())
File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 86, in main
args[0].func.main(args[1])
File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/main.py", line 234, in main
fasta_file_path = generate_fasta(args, tsv_file_path, output_dir)
File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/main.py", line 41, in generate_fasta
fasta_file_path
File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/generate_fasta.py", line 105, in main
position = int(line['protein_position']) - 1;
ValueError: invalid literal for int() with base 10: '771-772'

Input:
##fileformat=VCFv4.0
##VEP=v84 cache=homo_sapiens/84_GRCh37 db=. polyphen=2.2.2 sift=sift5.2.2 COSMIC=71 ESP=20141103 gencode=GENCODE 19 HGMD-PUBLIC=20152 genebuild=2011-04 regbuild=13 assembly=GRCh37.p13 dbSNP=144 ClinVar=201507
##DownstreamProtein=Predicted downstream translation for frameshift mutations
##ProteinLengthChange=Predicted change in protein product length
##WildtypeProtein=The normal, non-mutated protein sequence
##INFO=
#CHROM POS ID REF ALT QUAL FILTER INFO
4 140651584 . TCTGCTG T . PASS CSQ=-|inframe_deletion|MODERATE|MAML3|ENSG00000196782|Transcript|ENST00000509479|protein_coding|3/5||||3168-3173|2311-2316|771-772|QQ/-|CAGCAG/-|||-1||HGNC|16272|||MGDFAAPAAAANGSSICINSSLNSSLGGAGIGVNNTPNSTPAAPSSNHPAAGGCGGSGGPGGGSAAVPKHSTVVERLRQRIEGCRRHHVNCENRYQQAQVEQLELERRDTVSLYQRTLEQRAKKSGAGTGKQQHPSKPQQDAEAASAEQRNHTLIMLQETVKRKLEGARSPLNGDQQNGACDGNFSPTSKRIRKDISAGMEAINNLPSNMPLPSASPLHQLDLKPSLPLQNSGTHTPGLLEDLSKNGRLPEIKLPVNGCSDLEDSFTILQSKDLKQEPLDDPTCIDTSETSLSNQNKLFSDINLNDQEWQELIDELANTVPEDDIQDLFNEDFEEKKEPEFSQPATETPLSQESASVKSDPSHSPFAHVSMGSPQARPSSSGPPFSTVSTATSLPSVASTPAAPNPASSPANCAVQSPQTPNQAHTPGQAPPRPGNGYLLNPAAVTVAGSASGPVAVPSSDMSPAEQLKQMAAQQQQRAKLMQQKQQQQQQQQQQQQQQQQQQQQQQQQQHSNQTSNWSPLGPPSSPYGAAFTAEKPNSPMMYPQAFNNQNPIVPPMANNLQKTTMNNYLPQNHMNMINQQPNNLGTNSLNKQHNILTYGNTKPLTHFNADLSQRMTPPVANPNKNPLMPYIQQQQQQQQQQQQQQQQQQPPPPQLQAPRAHLSEDQKRLLLMKQKGVMNQPMAYAALPSHGQEQHPVGLPRTTGPMQSSVPPGSGGMVSGASPAGPGFLGSQPQAAIMKQMLIDQRAQLIEQQKQQFLREQRQQQQQQQQQILAEQQLQQSHLPRQHLQPQRNPYPVQQVNQFQGSPQDIAAVRSQAALQSMRTSRLMAQNAGMMGIGPSQNPGTMATAAAQSEMGLAPYSTTPTSQPGMYNMSTGMTQMLQHPNQSGMSITHNQAQGPRQPASGQGVGMVSGFGQSMLVNSAITQQHPQMKGPVGQALPRPQAPPRLQSLMGTVQQGAQSWQQRSLQGMPGRTSGELGPFNNGASYPLQAGQPRLTKQHFPQGLSQSVVDANTGTVRTLNPAAMGRQMMPSLPGQQGTSQARPMVMSGLSQGVPGMPAFSQPPAQQQIPSGSFAPSSQSQAYERNAPQDVSYNYSGDGAGGSFPGLPDGADLVDSIIKGGPGDEWMQELDELFGNP,-|inframe_deletion|MODERATE|MAML3|ENSG00000196782|Transcript|ENST00000502696|protein_coding|2/4||||342-347|343-348|115-116|QQ/-|CAGCAG/-|||-1|cds_start_NF&cds_end_NF|HGNC|16272|||XRAKKSGAGTGKQQHPSKPQQDAEAASAEQRNHTLIMEQHPVGLPRTTGPMQSSVPPGSGGMVSGASPAGPGFLGSQPQAAIMKQMLIDQRAQLIEQQKQQFLREQRQQQQQQQQQILAEQQLQQSHLPRQHLQPQRNPYPVQQVNQFQGSPQDIAAVRSQAALQSMRTSRLMAQNAGMMGIGPSQ,-|intron_variant&non_coding_transcript_variant|MODIFIER|MGST2|ENSG00000085871|Transcript|ENST00000515137|processed_transcript||4/4||||||||||1||HGNC|7063|||,-|3_prime_UTR_variant&NMD_transcript_variant|MODIFIER|MGST2|ENSG00000085871|Transcript|ENST00000503816|nonsense_mediated_decay|7/7||||776-781|||||||1||HGNC|7063|||MAGNSILLAAVSILSACQQSYFALQVGKARLKYKVTPPAVTGSPEFERVFRAQQNCVEFYPIFIITLWMAGWYFNQVFATCLGLVYIYGRHLYFWGYSEAAKKRITGFRLSLGILALLTLLGALGIANSFLDEYLDLNIAKKLRRQF GT:AD 0/1:23,14

**Comment by susannasiebert** [comment]
Thanks for the bug report. I will look into it as soon as possible.

**Comment by susannasiebert** [comment]
Do you happen to have encountered this issue with inframe inserts as well? If you do could you please post the vcf entry? This would greatly help us in covering all possible cases.

**Comment by pankajvats** [comment]
one more error message!!

 pvacseq run tt.merged.neo.vcf tt HLA-A*02:01 9,10 NetMHC Neo/ -l 21 --top-result-per-mutation 
Converting VCF to TSV
Completed
Generating Variant Peptide FASTA File
Traceback (most recent call last):
  File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 86, in main
    args[0].func.main(args[1])
  File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/main.py", line 234, in main
    fasta_file_path           = generate_fasta(args, tsv_file_path, output_dir)
  File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/main.py", line 41, in generate_fasta
    fasta_file_path
  File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/generate_fasta.py", line 85, in main
    for line in tsvin:
  File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/lib/python3.5/csv.py", line 110, in __next__
    row = next(self.reader)
_csv.Error: field larger than field limit (131072)

**Comment by susannasiebert** [comment]
This is a different error so I will make a new issue for it.

**Comment by pankajvats** [comment]
here is another type!!

pvacseq run pvaseq_test_error.vcf tt HLA-A*02:01 9,10 NetMHC Neo/ -l 21 --top-result-per-mutation
Converting VCF to TSV
Completed
Generating Variant Peptide FASTA File
Traceback (most recent call last):
File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/bin/pvacseq", line 11, in
sys.exit(main())
File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 86, in main
args[0].func.main(args[1])
File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/main.py", line 234, in main
fasta_file_path = generate_fasta(args, tsv_file_path, output_dir)
File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/main.py", line 41, in generate_fasta
fasta_file_path
File "pVAC-Seq/pVAC-Seq/conda/envs/snakes/lib/python3.5/site-packages/pvacseq/lib/generate_fasta.py", line 105, in main
position = int(line['protein_position']) - 1;
ValueError: invalid literal for int() with base 10: '168-177'

7	128587351	.	CACTCTGCAGCCGCCCACTCTGCGGCCGCCT	C	.	PASS	CSQ=-|downstream_gene_variant|MODIFIER|IRF5|ENSG00000128604|Transcript|ENST00000489702|protein_coding|||||||||||728|1|cds_end_NF|HGNC|6120|||MNQSIPVAPTPPRRVRLKPWLVAQVNSCQYPGLQWVNGEKKLFCIPWRHATRHGPSQDGDNTIFKAWAKETGKYTEGVDEADPAKWKANLRCALNKSRDFRLIYDGPRDMPPQPYKIYEVCSNGPAPTDSQPPEDYSFGAGEEEEEEEEVS,-|inframe_deletion|MODERATE|IRF5|ENSG00000128604|Transcript|ENST00000249375|protein_coding|6/9||||542-571|502-531|168-177|TLQPPTLRPP/-|ACTCTGCAGCCGCCCACTCTGCGGCCGCCT/-|||1||HGNC|6120|||MNQSIPVAPTPPRRVRLKPWLVAQVNSCQYPGLQWVNGEKKLFCIPWRHATRHGPSQDGDNTIFKAWAKETGKYTEGVDEADPAKWKANLRCALNKSRDFRLIYDGPRDMPPQPYKIYEVCSNGPAPTDSQPPEDYSFGAGEEEEEEEELQRMLPSLSLTEDVKWPPTLQPPTLRPPTLQPPTLQPPVVLGPPAPDPSPLAPPPGNPAGFRELLSEVLEPGPLPASLPPAGEQLLPDLLISPHMLPLTDLEIKFQYRGRPPRALTISNPHGCRLFYSQLEATQEQVELFGPISLEQVRFPSPEDIPSDKQRFYTNQLLDVLDRGLILQLQGQDLYAIRLCQCKVFWSGPCASAHDSCPNPIQREVKTKLFSLEHFLNELILFQKGQTNTPPPFEIFFCFGEEWPDRKPREKKLITVQVVPVAARLLLEMFSGELSWSADSIRLQISNPDLKDRMVEQFKELHHIWQSQQRLQPVAQAPPGAGLGVGQGPWPMHPAGMQ,-|downstream_gene_variant|MODIFIER|IRF5|ENSG00000128604|Transcript|ENST00000479582|protein_coding|||||||||||758|1|cds_end_NF|HGNC|6120|||MNQSIPVAPTPPRRVRLKPWLVAQVNSCQYPGLQWVNGEKKLFCIPWRHATRHGPSQDGDNTIFKAWAKETGKYTEGVDEADPAKWKANLRCALNKSRDFRLIYDGPRDMPPQPYKIYEVCSNGPAPTDSQPPEDYSFGAG,-|downstream_gene_variant|MODIFIER|IRF5|ENSG00000128604|Transcript|ENST00000488569|retained_intron|||||||||||356|1||HGNC|6120|||,-|3_prime_UTR_variant&NMD_transcript_variant|MODIFIER|IRF5|ENSG00000128604|Transcript|ENST00000465603|nonsense_mediated_decay|6/9||||523-552|||||||1||HGNC|6120|||MNQSIPVAPTPPRRVRLKPWLVAQVNSCQYPGLQWVNGEKKLFCIPWRHATRHGPSQDGDNTIFKAWAKETGKYTEGVDEADPAKWKANLRCALNKSRDFRLIYDGPRDMPPQPYKIYETPSPLRITLLVQERRRKKRKSCRGCCQA,-|downstream_gene_variant|MODIFIER|IRF5|ENSG00000128604|Transcript|ENST00000473787|nonsense_mediated_decay|||||||||||742|1||HGNC|6120|||MNQSIPVAPTPPRRVRLKPWLVAQVNSCQYPGLQWVNGEKKLFCIPWRHATRHGPSQDGDNTIFKGLTLSPRLECSGLISAHCSLDLPGSGLGQGDREIHRRRG,-|non_coding_transcript_exon_variant&non_coding_transcript_variant|MODIFIER|IRF5|ENSG00000128604|Transcript|ENST00000461416|retained_intron|5/6||||803-832|||||||1||HGNC|6120|||,-|inframe_deletion|MODERATE|IRF5|ENSG00000128604|Transcript|ENST00000357234|protein_coding|6/9||||671-700|550-579|184-193|TLQPPTLRPP/-|ACTCTGCAGCCGCCCACTCTGCGGCCGCCT/-|||1||HGNC|6120|||MNQSIPVAPTPPRRVRLKPWLVAQVNSCQYPGLQWVNGEKKLFCIPWRHATRHGPSQDGDNTIFKAWAKETGKYTEGVDEADPAKWKANLRCALNKSRDFRLIYDGPRDMPPQPYKIYEVCSNGPAPTDSQPPEDYSFGAGEEEEEEEELQRMLPSLSLTDAVQSGPHMTPYSLLKEDVKWPPTLQPPTLRPPTLQPPTLQPPVVLGPPAPDPSPLAPPPGNPAGFRELLSEVLEPGPLPASLPPAGEQLLPDLLISPHMLPLTDLEIKFQYRGRPPRALTISNPHGCRLFYSQLEATQEQVELFGPISLEQVRFPSPEDIPSDKQRFYTNQLLDVLDRGLILQLQGQDLYAIRLCQCKVFWSGPCASAHDSCPNPIQREVKTKLFSLEHFLNELILFQKGQTNTPPPFEIFFCFGEEWPDRKPREKKLITVQVVPVAARLLLEMFSGELSWSADSIRLQISNPDLKDRMVEQFKELHHIWQSQQRLQPVAQAPPGAGLGVGQGPWPMHPAGMQ,-|inframe_deletion|MODERATE|IRF5|ENSG00000128604|Transcript|ENST00000473745|protein_coding|6/9||||717-746|502-531|168-177|TLQPPTLRPP/-|ACTCTGCAGCCGCCCACTCTGCGGCCGCCT/-|||1||HGNC|6120|||MNQSIPVAPTPPRRVRLKPWLVAQVNSCQYPGLQWVNGEKKLFCIPWRHATRHGPSQDGDNTIFKAWAKETGKYTEGVDEADPAKWKANLRCALNKSRDFRLIYDGPRDMPPQPYKIYEVCSNGPAPTDSQPPEDYSFGAGEEEEEEEELQRMLPSLSLTEDVKWPPTLQPPTLRPPTLQPPTLQPPVVLGPPAPDPSPLAPPPGNPAGFRELLSEVLEPGPLPASLPPAGEQLLPDLLISPHMLPLTDLEIKFQYRGRPPRALTISNPHGCRLFYSQLEATQEQVELFGPISLEQVRFPSPEDIPSDKQRFYTNQLLDVLDRGLILQLQGQDLYAIRLCQCKVFWSGPCASAHDSCPNPIQREVKTKLFSLEHFLNELILFQKGQTNTPPPFEIFFCFGEEWPDRKPREKKLITVQVVPVAARLLLEMFSGELSWSADSIRLQISNPDLKDRMVEQFKELHHIWQSQQRLQPVAQAPPGAGLGVGQGPWPMHPAGMQ,-|downstream_gene_variant|MODIFIER|IRF5|ENSG00000128604|Transcript|ENST00000464557|protein_coding|||||||||||1331|1|cds_end_NF|HGNC|6120|||MNQSIPVAPTPPRRVRLKPWLVAQVNSCQYPGLQWVNGEKKLFCIPWRHATRHGPSQDGDNTIFKAWAKETGKYTEGVDEADPAKWKANLRCALNKSRDFRLIYDG,-|inframe_deletion|MODERATE|IRF5|ENSG00000128604|Transcript|ENST00000402030|protein_coding|6/9||||574-603|502-531|168-177|TLQPPTLRPP/-|ACTCTGCAGCCGCCCACTCTGCGGCCGCCT/-|||1||HGNC|6120|||MNQSIPVAPTPPRRVRLKPWLVAQVNSCQYPGLQWVNGEKKLFCIPWRHATRHGPSQDGDNTIFKAWAKETGKYTEGVDEADPAKWKANLRCALNKSRDFRLIYDGPRDMPPQPYKIYEVCSNGPAPTDSQPPEDYSFGAGEEEEEEEELQRMLPSLSLTEDVKWPPTLQPPTLRPPTLQPPTLQPPVVLGPPAPDPSPLAPPPGNPAGFRELLSEVLEPGPLPASLPPAGEQLLPDLLISPHMLPLTDLEIKFQYRGRPPRALTISNPHGCRLFYSQLEATQEQVELFGPISLEQVRFPSPEDIPSDKQRFYTNQLLDVLDRGLILQLQGQDLYAIRLCQCKVFWSGPCASAHDSCPNPIQREVKTKLFSLEHFLNELILFQKGQTNTPPPFEIFFCFGEEWPDRKPREKKLITVQVVPVAARLLLEMFSGELSWSADSIRLQISNPDLKDRMVEQFKELHHIWQSQQRLQPVAQAPPGAGLGVGQGPWPMHPAGMQ,-|intron_variant|MODIFIER|IRF5|ENSG00000128604|Transcript|ENST00000477535|protein_coding||5/7||||||||||1||HGNC|6120|||MNQSIPVAPTPPRRVRLKPWLVAQVNSCQYPGLQWVNGEKKLFCIPWRHATRHGPSQDGDNTIFKAWAKETGKYTEGVDEADPAKWKANLRCALNKSRDFRLIYDGPRDMPPQPYKIYEVCSNGPAPTDSQPPEDYSFGAGEEEEEEEELQRMLPSLSLTVTDLEIKFQYRGRPPRALTISNPHGCRLFYSQLEATQEQVELFGPISLEQVRFPSPEDIPSDKQRFYTNQLLDVLDRGLILQLQGQDLYAIRLCQCKVFWSGPCASAHDSCPNPIQREVKTKLFSLEHFLNELILFQKGQTNTPPPFEIFFCFGEEWPDRKPREKKLITVQVVPVAARLLLEMFSGELSWSADSIRLQISNPDLKDRMVEQFKELHHIWQSQQRLQPVAQAPPGAGLGVGQGPWPMHPAGMQ	GT:AD	0/1:313,153

**Comment by pankajvats** [comment]
i don't see any inframe inserts causing this error !!

**Comment by susannasiebert** [comment]
Version 3.0.5 should fix this issue.
