### ISSUE TITLE
difference in Sub-peptide Position: IEDB (used since pVAC-Seq 3.0) vs. NetMHC3.4 (used in pVAC-Seq 2.0)

### ISSUE THREAD

**Issue by maciejrosolowski** [griffithlab/pVAC-Seq#166]
It seems that the sub-peptide position in the output of NetMHC3.4 (column "pos") starts from zero but the sub-peptide position used in IEDB (column "Start") starts from one. The former is used in the older versions of pVAC-Seq, e.g., 2.0.0, and the latter is used in the newer versions, e.g., 3.05. As a consequence, the column "Sub-peptide Position" in the output file of pVAC-Seq differs between these two pVAC-Seq versions (by 1).

Example:
[input_protein_sequence.txt](https://github.com/griffithlab/pVAC-Seq/files/436889/input_protein_sequence.txt)
Output from NetMHC3.4:
[result_NetMHC3_4.txt](https://github.com/griffithlab/pVAC-Seq/files/436895/result_NetMHC3_4.txt)
Output from IEDB:
[result_IEDB.txt](https://github.com/griffithlab/pVAC-Seq/files/436896/result_IEDB.txt)

**Comment by susannasiebert** [comment]
With pVAC-Seq 3.0.0 we started using IEDB on the backend for making binding predictions. IEDB uses a 1-base as the standard for the sub-peptide position which we subsequently adopted in pVAC-Seq. As such the sub-peptide position will be off by one between pVAC-Seq 3.0.0 and previous versions.
