### ISSUE TITLE
Filter fasta entries where the sequence is too short

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVAC-Seq#168]
IEDB errors out when the fasta is shorter then 9 amino acids for class II predictions. It might also error out for class I for this reason.

**Comment by kcampbel** [comment]
>2	158795373	2-158795373-158795374	N	NT	.	.	CSQ=T|frameshift_variant&start_lost|HIGH|DAPL1|ENSG00000163331|Transcript|ENST00000309950|protein_coding|1/4||||57-58|1-2|1|M/IX|atg/aTtg|||1||HGNC|HGNC:21490|IGK|-103|MANEVQDLLSPRKGGHPPAVKAGGMRISKKQEIGTLERHTKKTGFEKTSAIANVAKIQTLDALNDALEKLNYKFPATVHMAHQKPTPALEKVVPLKRIYIIQQPRKC,T|frameshift_variant&start_lost|HIGH|DAPL1|ENSG00000163331|Transcript|ENST00000409042|protein_coding|1/5||||57-58|1-2|1|M/IX|atg/aTtg|||1||HGNC|HGNC:21490|IGK|-109|MANEVQDLLSPRKGGHPPAVKAGGMRISKKQEIGTLERHTKKTGFEKTSAIANVAKIQTLDALNDALEKEQVQLGVRNERQVQPFHHGCSWKETSGFDTRCPRHTEPRNLTGV,T|frameshift_variant&start_lost|HIGH|DAPL1|ENSG00000163331|Transcript|ENST00000619477|protein_coding|1/5||||16-17|1-2|1|M/IX|atg/aTtg|||1||HGNC|HGNC:21490|IGK|-195|MANEVQDLLSPRKGGHPPAVKAGGMRISKKQEIGTLERHTKKTGFEKTSAIANVAKIQTLDALNDALEKEQVQLGVRNERQVQPFHHGCSWKETSGFDTRSSEDPERLFLSMCLVTVLGNLLIILAVTPDSHLHIPMYFFLSNLSLPDIGFTSTTVPKMIVDIQSHSRVISYAGCLTQMSLFAIFGGMEERHAPECDGL,T|frameshift_variant&start_lost|HIGH|DAPL1|ENSG00000163331|Transcript|ENST00000621326|protein_coding|1/5||||57-58|1-2|1|M/IX|atg/aTtg|||1||HGNC|HGNC:21490|IGK|-130|MANEVQDLLSPRKGGHPPAVKAGGMRISKKQEIGTLERHTKKTGFEKTSAIANVAKIQTLDALNDALEKSFALFAQAGKQWSDLSSLQPPPPGFKWFSCLSLPSSWDYSSTINFQQQCTWRIKNPHLLWKRLFH
