### ISSUE TITLE
Run Integrate on HCC1395 tumor RNA-seq for GRCh37-lite.

### ISSUE THREAD

**Issue by jasonwalker80** [griffithlab/pVAC-Seq#184]

**Comment by jasonwalker80** [comment]
https://github.com/ChrisMaherLab/INTEGRATE/issues/2

**Comment by jasonwalker80** [comment]
@susannasiebert I'm running Integrate on the HCC1395 ClinSeq Model Test, Tumor RNA + Paired WGS.  My working directory:
/gscuser/jwalker/git/HCC1395/integrate/GRCh37/

**Comment by jasonwalker80** [comment]
Early this morning, after almost 14 hours, this ran out of RAM with a limit of 32GB.  I'll try again with 64GB.

**Comment by jasonwalker80** [comment]
Integrate finished and I have run INTEGRATE-neo `fusionBedpeAnnotator`.  The resulting file on MGI disk is located:
`/gscuser/jwalker/git/HCC1395/integrate/GRCh37/fusions_annotated.bedpe`

**Comment by susannasiebert** [comment]
Do we know what each of the columns represents?

**Comment by malachig** [comment]
The docs here are quite limited:
https://sourceforge.net/p/integrate-fusion/wiki/output/

Can you post a snippet here?

**Comment by jasonwalker80** [comment]
Also see #76 for column info

**Comment by chrisamiller** [comment]
FWIW, here's how I run INTEGRATE:

`bsubBigger -J integrate "/gscuser/cmiller/usr/src/INTEGRATE_0_2/INTEGRATE-build/bin/Integrate fusion /gscuser/tli/gc3018/genome/ams1102/all_sequences.fa /gscuser/tli/gc3018/genome/bwts/ /gscmnt/gc1403/prod-builder/model_data/458037ca2694454f9effafea7c5a8635/buildb73cf6e1b45f4bf9a92eb18b80429760/alignments/3d3e23a6992e4fea9aee70b34f84a22c.bam /gscmnt/gc1403/prod-builder/model_data/458037ca2694454f9effafea7c5a8635/buildb73cf6e1b45f4bf9a92eb18b80429760/alignments/3d3e23a6992e4fea9aee70b34f84a22c.bam /gscmnt/gc1403/prod-builder/build_merged_alignments/merged-alignment-blade17-2-16.gsc.wustl.edu-prod-builder-1-cb52b53bfcce4071bcc48a5c62760658/cb52b53bfcce4071bcc48a5c62760658.bam /gscmnt/gc1403/prod-builder/build_merged_alignments/merged-alignment-blade17-2-5.gsc.wustl.edu-prod-builder-1-015d98dc477141318dbfa5cb1228f497/015d98dc477141318dbfa5cb1228f497.bam`

**Comment by jasonwalker80** [comment]
I now have a HISAT2 BAM file for HCC1395 tumor RNA.  I expect this BAM will yield better fusion predictions as it allows for split read mapping and should handle shorter inserts better.  I ran Integrate over the weekend with 32GB of RAM, but it failed.  I'm running again with 64GB of RAM: 
`JOBID   USER    STAT  QUEUE      FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME
8975701 jwalker PEND  long       linus2112.gsc.wustl.edu    -        /gscuser/jwalker/git/HCC1395/integrate/GRCh37/software/INTEGRATE_0_2_6/INTEGRATE-build/bin/Integrate fusion /gscmnt/ams1102/info/model_data/2869585698/build106942997/all_sequences.fa /gscuser/jwalker/git/HCC1395/integrate/GRCh37/annotation/annot.enseml.GRCh37.txt /gscuser/jwalker/git/HCC1395/integrate/GRCh37/bwts /gscmnt/gc13001/info/model_data/jwalker_scratch/HCC1395/rna_seq/GRCh37/alignments/H_NJ-HCC1395-HCC1395_RNA.bam /gscmnt/gc13001/info/model_data/jwalker_scratch/HCC1395/rna_seq/GRCh37/alignments/H_NJ-HCC1395-HCC1395_RNA.bam /gscmnt/gc8002/info/build_merged_alignments/merged-alignment-blade13-2-11.gsc.wustl.edu-jwalker-27691-f1e64d1802b0493095d70b837a467f47/f1e64d1802b0493095d70b837a467f47.bam Sep 27 09:59`
