### ISSUE TITLE
Restarting recreates fasta file

### ISSUE THREAD

**Issue by chrisamiller** [griffithlab/pVAC-Seq#191]
With large fasta files, I seem to inevitably hit an IEDB timeout.  Every time I go to restart one of these 'pvacseq run' jobs, it recreates the peptide fasta, which can take a long time. It would be good to add a "--resume" flag to `pvacseq run`, so that when you restart a job, it can use the existing fasta, as well as the existing iedb results.  (or maybe just have it look automatically without needing a flag)

**Comment by susannasiebert** [comment]
Ok, we should discuss this workflow in more detail. Currently all files in tmp will be skipped if they already exist and will not be reprocessed. If we introduce a `--resume` flag I would expect the behavior to be that by default we never reprocess any files which would diverge from the current behavior. The alternative is to have a `--reprocess-existing` flag which would reprocess the files. The default would then be to skip existing files.

Would we also wan to start skipping the reprocessing of downstream files like the combined file and the filtered files? My vote is to always reprocess downstream files (including the combined file and all following steps).

**Comment by chrisamiller** [comment]
I agree that combined/filtered files should be reprocessed, as if you're not changing those, then there's no reason to be running pvacseq again, right?  I get what you're saying - I just think the automatic resumption should also apply to the steps upstream of the tmp file creation.  Maybe this doesn't even require a flag at all

**Comment by susannasiebert** [comment]
Ok, we can definitely just keep the current workflow but add the tsv and the fasta to the list of files that don't get reprocessed if they already exist.
