### ISSUE TITLE
Question about frameshift indel. 

### ISSUE THREAD

**Issue by pankajvats** [griffithlab/pVAC-Seq#201]
how are you calculating the frame information for the indels here is one example
when i looked for the peptide it should be but the pvacseq out put was different
FS del of A
ex-
chr2  74274462 74274463  TA  T 
wt coding seq: _SASDYIQSVF_
mt seq should be :_SASDSSSQY_...
but output is:
>WT.TET3_ENST00000409262_1.FS.338
EQLLGSASD**Y**IQSVFKRP
>MT.TET3_ENST00000409262_1.FS.338
EQLLGSASD**I**QSVFKRPEALPTKPKVKVEAPSSSPAPAPSPVLQREAPTPSSEPDTHQKAQTALQQHLHHKRSLFLEQVHDTSFPAPSEPSAPGWWPPPSSPVPRLPDRPPKEKKKKLPTPAGGPVGTEKAAPGIKPSVRKPIQIKKSRPREAQPLFPPVRQIVLEGLRSPASQEVQAHPPAPLPASQGSAVPLPPEPSLALFAPSPSRDSLLPPTQEMRSPSPMTALQPGSTGPLPPADD

**Comment by susannasiebert** [comment]
Can you please post the vcf entry for this variant?

When creating the fasta entries we parse all of the information from the CSQ field in the VCF. For frameshifts we look at the protein position (338) and the downstream sequence that is encoded in the CSQ field. We take 9 (in your case) amino acids before the mutation and append the downstream sequence to it. From what you are posting I think downstream sequence encoded in the VCF is `IQSVFKRPEALPTKPK...` but I would like to see the vcf entry to confirm.

**Comment by pankajvats** [comment]
annotated vcf:

##fileformat=VCFv4.0
##fileDate=20101123
####source=pindel
####reference=1000GenomePilot-NCBI37
####INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
####INFO=<ID=HOMLEN,Number=1,Type=Integer,Description="Length of base pair identical micro-homology at event breakpoints">
####INFO=<ID=PF,Number=1,Type=Integer,Description="The number of samples carry the variant">
####INFO=<ID=HOMSEQ,Number=.,Type=String,Description="Sequence of base pair identical micro-homology at event breakpoints">
####INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Difference in length between REF and ALT alleles">
####INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
####INFO=<ID=NTLEN,Number=.,Type=Integer,Description="Number of bases inserted in place of deleted code">
####FORMAT=<ID=PL,Number=3,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
####FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
####FORMAT=<ID=RD,Number=1,Type=Integer,Description="Reference depth, how many reads support the reference">
####FORMAT=<ID=AD,Number=2,Type=Integer,Description="Allele depth, how many reads support this allele">
##VEP=v84 cache=/home/pankajv/.vep/homo_sapiens/84_GRCh37 db=. polyphen=2.2.2 sift=sift5.2.2 COSMIC=71 ESP=20141103 gencode=GENCODE 19 HGMD-PUBLIC=20152 genebuild=2011-04 regbuild=13 assembly=GRCh37.p13 dbSNP=144 ClinVar=201507
##DownstreamProtein=Predicted downstream translation for frameshift mutations
##ProteinLengthChange=Predicted change in protein product length
##WildtypeProtein=The normal, non-mutated protein sequence
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|DownstreamProtein|ProteinLengthChange|WildtypeProtein">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TumorLib
2	74274462	.	TA	T	.	PASS	0/1498:0/1498;CSQ=-|frameshift_variant&stop_lost|HIGH|TET3|ENSG00000187605|Transcript|ENST00000409262|protein_coding|1/9||||1014|1014|338|*/X|taA/ta|||1||HGNC|28313|IQSVFKRPEALPTKPKVKVEAPSSSPAPAPSPVLQREAPTPSSEPDTHQKAQTALQQHLHHKRSLFLEQVHDTSFPAPSEPSAPGWWPPPSSPVPRLPDRPPKEKKKKLPTPAGGPVGTEKAAPGIKPSVRKPIQIKKSRPREAQPLFPPVRQIVLEGLRSPASQEVQAHPPAPLPASQGSAVPLPPEPSLALFAPSPSRDSLLPPTQEMRSPSPMTALQPGSTGPLPPADDKLEELIRQFEAEFGDSFGLPGPPSVPIQDPENQQTCLPAPESPFATRSPKQIKIESSGAVTVLSTTCFHSEEGGQEATPTKAENPLTPTLSGFLESPLKYLDTPTKSLLDTPAKRAQAEFPTCDCVEQIVEKDEGPYYTHLGSGPTVASIRELMEERYGEKGKAIRIEKVIYTGKEGKSSRGCPIAKWVIRRHTLEEKLLCLVRHRAGHHCQNAVIVILILAWEGIPRSLGDTLYQELTDTLRKYGNPTSRRCGLNDDRTCACQGKDPNTCGASFSFGCSWSMYFNGCKYARSKTPRKFRLAGDNPKEEEVLRKSFQDLATEVAPLYKRLAPQAYQNQVTNEEIAIDCRLGLKEGRPFAGVTACMDFCAHAHKDQHNLYNGCTVVCTLTKEDNRCVGKIPEDEQLHVLPLYKMANTDEFGSEENQNAKVGSGAIQVLTAFPREVRRLPEPAKSCRQRQLEARKAAAEKKKIQKEKLSTPEKIKQEALELAGITSDPGLSLKGGLSQQGLKPSLKVEPQNHFSSFKYSGNAVVESYSVLGNCRPSDPYSMNSVYSYHSYYAQPSLTSVNGFHSKYALPSFSYYGFPSSNPVFPSQFLGPGAWGHSGSSGSFEKKPDLHALHNSLSPAYGGAEFAELPSQAVPTDAHHPTPHHQQPAYPGPKEYLLPKAPLLHSVSRDPSPFAQSSNCYNRSIKQEPVDPLTQAEPVPRDAGKMGKTPLSEVSQNGGPSHLWGQYSGGPSMSPKRTNGVGGSWGVFSSGESPAIVPDKLSSFGASCLAPSHFTDGQWGLFPGEGQQAASHSGGRLRGKPWSPCKFGNSTSALAGPSLTEKPWALGAGDFNSALKGSPGFQDKLWNPMKGEEGRIPAAGASQLDRAWQSFGLPLGSSEKLFGALKSEEKLWDPFSLEEGPAEEPPSKGAVKEEKGGGGAEEEEEELWSDSEHNFLDENIGGVAVAPAHGSILIECARRELHATTPLKKPNRCHPTRISLVFYQHKNLNQPNHGLALWEAKMKQLAERARARQEEAARLGLGQQEAKLYGKKRKWGGTVVAEPQQKEKKGVVPTRQALAVPTDSAVTVSSYAYTKVTGPYSRWI|0|MDSGPVYHGDSRQLSASGVPVNGAREPAGPSLLGTGGPWRVDQKPDWEAAPGPAHTARLEDAHDLVAFSAVAEAVSSYGALSTRLYETFNREMSREAGNNSRGPRPGPEGCSAGSEDLDTLQTALALARHGMKPPNCNCDGPECPDYLEWLEGKIKSVVMEGGEERPRLPGPLPPGEAGLPAPSTRPLLSSEVPQISPQEGLPLSQSALSIAKEKNISLQTAIAIEALTQLSSALPQPSHSTPQASCPLPEALSPPAPFRSPQSYLRAPSWPVVPPEEHSSFAPDSSAFPPATPRTEFPEAWGTDTPPATPRSSWPMPRPSPDPMAELEQLLGSASDYIQSVFKRPEALPTKPKVKVEAPSSSPAPAPSPVLQREAPTPSSEPDTHQKAQTALQQHLHHKRSLFLEQVHDTSFPAPSEPSAPGWWPPPSSPVPRLPDRPPKEKKKKLPTPAGGPVGTEKAAPGIKPSVRKPIQIKKSRPREAQPLFPPVRQIVLEGLRSPASQEVQAHPPAPLPASQGSAVPLPPEPSLALFAPSPSRDSLLPPTQEMRSPSPMTALQPGSTGPLPPADDKLEELIRQFEAEFGDSFGLPGPPSVPIQDPENQQTCLPAPESPFATRSPKQIKIESSGAVTVLSTTCFHSEEGGQEATPTKAENPLTPTLSGFLESPLKYLDTPTKSLLDTPAKRAQAEFPTCDCVEQIVEKDEGPYYTHLGSGPTVASIRELMEERYGEKGKAIRIEKVIYTGKEGKSSRGCPIAKWVIRRHTLEEKLLCLVRHRAGHHCQNAVIVILILAWEGIPRSLGDTLYQELTDTLRKYGNPTSRRCGLNDDRTCACQGKDPNTCGASFSFGCSWSMYFNGCKYARSKTPRKFRLAGDNPKEEEVLRKSFQDLATEVAPLYKRLAPQAYQNQVTNEEIAIDCRLGLKEGRPFAGVTACMDFCAHAHKDQHNLYNGCTVVCTLTKEDNRCVGKIPEDEQLHVLPLYKMANTDEFGSEENQNAKVGSGAIQVLTAFPREVRRLPEPAKSCRQRQLEARKAAAEKKKIQKEKLSTPEKIKQEALELAGITSDPGLSLKGGLSQQGLKPSLKVEPQNHFSSFKYSGNAVVESYSVLGNCRPSDPYSMNSVYSYHSYYAQPSLTSVNGFHSKYALPSFSYYGFPSSNPVFPSQFLGPGAWGHSGSSGSFEKKPDLHALHNSLSPAYGGAEFAELPSQAVPTDAHHPTPHHQQPAYPGPKEYLLPKAPLLHSVSRDPSPFAQSSNCYNRSIKQEPVDPLTQAEPVPRDAGKMGKTPLSEVSQNGGPSHLWGQYSGGPSMSPKRTNGVGGSWGVFSSGESPAIVPDKLSSFGASCLAPSHFTDGQWGLFPGEGQQAASHSGGRLRGKPWSPCKFGNSTSALAGPSLTEKPWALGAGDFNSALKGSPGFQDKLWNPMKGEEGRIPAAGASQLDRAWQSFGLPLGSSEKLFGALKSEEKLWDPFSLEEGPAEEPPSKGAVKEEKGGGGAEEEEEELWSDSEHNFLDENIGGVAVAPAHGSILIECARRELHATTPLKKPNRCHPTRISLVFYQHKNLNQPNHGLALWEAKMKQLAERARARQEEAARLGLGQQEAKLYGKKRKWGGTVVAEPQQKEKKGVVPTRQALAVPTDSAVTVSSYAYTKVTGPYSRWI	GT:AD	110/661(17%);110/661(16.64%)
10	89711879	.	GTAAC	G	.	PASS	0/1498:0/1498;CSQ=-|frameshift_variant|HIGH|PTEN|ENSG00000171862|Transcript|ENST00000371953|protein_coding|6/9||||1855-1858|498-501|166-167|VN/X|gtTAAC/gt|||1||HGNC|9588|TIPSQRRYVYYYSYLLKNHLDYRPVALLFHKMMFETIPMFSGGTCNPQFVVCQLKVKIYSSNSGPTRREDKFMYFEFPQPLPVCGDIKVEFFHKQNKMLKKDKMFHFWVNTFFIPGPEETSEKVENGSLCDQEIDSICSIERADNDKEYLVLTLTKNDLDKANKDKANRYFSPNFKVKLYFTKTVEEPSNPEASSSTSVTPDVSDNEPDHYRYSDTTDSDPENEPFDEDQHTQITKV|0|MTAIIKEIVSRNKRRYQEDGFDLDLTYIYPNIIAMGFPAERLEGVYRNNIDDVVRFLDSKHKNHYKIYNLCAERHYDTAKFNCRVAQYPFEDHNPPQLELIKPFCEDLDQWLSEDDNHVAAIHCKAGKGRTGVMICAYLLHRGKFLKAQEALDFYGEVRTRDKKGVTIPSQRRYVYYYSYLLKNHLDYRPVALLFHKMMFETIPMFSGGTCNPQFVVCQLKVKIYSSNSGPTRREDKFMYFEFPQPLPVCGDIKVEFFHKQNKMLKKDKMFHFWVNTFFIPGPEETSEKVENGSLCDQEIDSICSIERADNDKEYLVLTLTKNDLDKANKDKANRYFSPNFKVKLYFTKTVEEPSNPEASSSTSVTPDVSDNEPDHYRYSDTTDSDPENEPFDEDQHTQITKV	GT:AD	32/329(10%);32/329(9.73%)
15	45007766	.	ATTCAGAC	A	.	PASS	0/1498:0/1498;CSQ=-|frameshift_variant|HIGH|B2M|ENSG00000166710|Transcript|ENST00000558401|protein_coding|2/4||||284-290|214-220|72-74|FRL/X|TTCAGACtg/tg|||1||HGNC|914|CLSARTGLSISCTTLNSPPLKKMSMPAV|-19|MSRSVALAVLALLSLSGLEAIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM	GT:AD	109/1043(10%);109/1043(10.45%)
15	66995972	.	CT	C	.	PASS	0/1498:0/1498;CSQ=-|frameshift_variant|HIGH|SMAD6|ENSG00000137834|Transcript|ENST00000288840|protein_coding|1/4||||1408|377|126|F/X|tTc/tc|||1||HGNC|6772|SVSFRSGTPPARPGTPATPWPGRPWSRRAAGGVAKRARGCCCWSRNSKPSRTRC|-316|MFRSKRSGLVRRLWRSRVVPDREEGGSGGGGGGDEDGSLGSRAEPAPRAREGGGCGRSEVRPVAPRRPRDAVGQRGAQGAGRRRRAGGPPRPMSEPGAGAGSSLLDVAEPGGPGWLPESDCETVTCCLFSERDAAGAPRDASDPLAGAALEPAGGGRSREARSRLLLLEQELKTVTYSLLKRLKERSLDTLLEAVESRGGVPGGCVLVPRADLRLGGQPAPPQLLLGRLFRWPDLQHAVELKPLCGCHSFAAAADGPTVCCNPYHFSRLCGPESPPPPYSRLSPRDEYKPLDLSDSTLSYTETEATNSLITAPGEFSDASMSPDATKPSHWCSVAYWEHRTRVGRLYAVYDQAVSIFYDLPQGSGFCLGQLNLEQRSESVRRTRSKIGFGILLSKEPDGVWAYNRGEHPIFVNSPTLDAPGGRALVVRKVPPGYSIKVFDFERSGLQHAPEPDAADGPYDPNSVRISFAKGWGPCYSRQFITSCPCWLEILLNNPR	GT:AD	61/455(13%);61/455(13.41%)
21	37416178	.	TACCTCTTC	T	.	PASS	0/1498:0/1498;CSQ=-|frameshift_variant|HIGH|SETD4|ENSG00000185917|Transcript|ENST00000399215|protein_coding|6/10||||2168-2175|795-802|265-268|QKRL/HX|caGAAGAGGTta/cata|||-1||HGNC|1258|EEVFICYGPHDNQRLFLEYGFVSVHNPHACVYVSREILVKYLPSTDKQMDKKISILKDHGYIENLTFGWDGPSWRLLTALKLLCLEAEKFTCWKKVLLGEVISDTNEKTSLDIAQKICYYFIEETNAVLQKVSHMKDEKEALINQLTLVESLWTEELKILRASAETLHSLQTAFTCIHLLRPSR|9|MQKGKGRTSRIRRRKLCGSSESRGVNESHKSEFIELRKWLKARKFQDSNLAPACFPGTGRGLMSQTSLQEGQMIISLPESCLLTTDTVIRSYLGAYITKWKPPPSPLLALCTFLVSEKHAGHRSLWKPYLEILPKAYTCPVCLEPEVVNLLPKSLKAKAEEQRAHVQEFFASSRDFFSSLQPLFAEAVDSIFSYSALLWAWCTVNTRAVYLRPRQRECLSAEPDTCALAPYLDLLNHSPHVQVKAAFNEETHSYEIRTTSRWRKHEEVFICYGPHDNQRLFLEYGFVSVHNPHACVYVSREILVKYLPSTDKQMDKKISILKDHGYIENLTFGWDGPSWRLLTALKLLCLEAEKFTCWKKVLLGEVISDTNEKTSLDIAQKICYYFIEETNAVLQKVSHMKDEKEALINQLTLVESLWTEELKILRASAETLHSLQTAFT	GT:AD	131/1031(13%);131/983(13.33%)
4	149356413	.	A	ATATT	.	PASS	0/1498:0/1498;CSQ=TATT|frameshift_variant|HIGH|NR3C2|ENSG00000151623|Transcript|ENST00000358102|protein_coding|2/9||||1962-1963|1599-1600|533-534|-/NX|-/AATA|||-1||HGNC|7979|NIFITIG|-444|METKGYHSLPEGLDMERRWGQVSQAVERSSLGPTERTDENNYMEIVNVSCVSGAIPNNSTQGSSKEKQELLPCLQQDNNRPGILTSDIKTELESKELSATVAESMGLYMDSVRDADYSYEQQNQQGSMSPAKIYQNVEQLVKFYKGNGHRPSTLSCVNTPLRSFMSDSGSSVNGGVMRAVVKSPIMCHEKSPSVCSPLNMTSSVCSPAGINSVSSTTASFGSFPVHSPITQGTPLTCSPNVENRGSRSHSPAHASNVGSPLSSPLSSMKSSISSPPSHCSVKSPVSSPNNVTLRSSVSSPANINNSRCSVSSPSNTNNRSTLSSPAASTVGSICSPVNNAFSYTASGTSAGSSTLRDVVPSPDTQEKGAQEVPFPKTEEVESAISNGVTGQLNIVQYIKPEPDGAFSSSCLGGNSKINSDSSFSVPIKQESTKHSCSGTSFKGNPTVNPFPFMDGSYFSFMDDKDYYSLSGILGPPVPGFDGNCEGSGFPVGIKQEPDDGSYYPEASIPSSAIVGVNSGGQSFHYRIGAQGTISLSRSARDQSFQHLSSFPPVNTLVESWKSHGDLSSRRSDGYPVLEYIPENVSSSTLRSVSTGSSRPSKICLVCGDEASGCHYGVVTCGSCKVFFKRAVEGQHNYLCAGRNDCIIDKIRRKNCPACRLQKCLQAGMNLGARKSKKLGKLKGIHEEQPQQQQPPPPPPPPQSPEEGTTYIAPAKEPSVNTALVPQLSTISRALTPSPVMVLENIEPEIVYAGYDSSKPDTAENLLSTLNRLAGKQMIQVVKWAKVLPGFKNLPLEDQITLIQYSWMCLSSFALSWRSYKHTNSQFLYFAPDLVFNEEKMHQSAMYELCQGMHQISLQFVRLQLTFEEYTIMKVLLLLSTIPKDGLKSQAAFEEMRTNYIKELRKMVTKCPNNSGQSWQRFYQLTKLLDSMHDLVSDLLEFCFYTFRESHALKVEFPAMLVEIISDQLPKVESGNAKPLYFHRK	GT:AD	112/1039(11%);112/1039(10.78%)
14	38061849	.	T	TC	.	PASS	0/1498:0/1498;CSQ=C|stop_gained&frameshift_variant|HIGH|FOXA1|ENSG00000129514|Transcript|ENST00000250448|protein_coding|2/2||||201-202|139-140|47|Y/*|tac/tGac|||-1||HGNC|5021||-425|MLGTVKMEGHETSDWNSYYADTQEAYSSVPVSNMNSGLGSMNSMNTYMTMNTMTTSGNMTPASFNMSYANPGLGAGLSPGAVAGMPGGSAGAMNSMTAAGVTAMGTALSPSGMGAMGAQQAASMNGLGPYAAAMNPCMSPMAYAPSNLGRSRAGGGGDAKTFKRSYPHAKPPYSYISLITMAIQQAPSKMLTLSEIYQWIMDLFPYYRQNQQRWQNSIRHSLSFNDCFVKVARSPDKPGKGSYWTLHPDSGNMFENGCYLRRQKRFKCEKQPGAGGGGGSGSGGSGAKGGPESRKDPSGASNPSADSPLHRGVHGKTGQLEGAPAPGPAASPQTLDHSGATATGGASELKTPASSTAPPISSGPGALASVPASHPAHGLAPHESQLHLKGDPHYSFNHPFSINNLMSSSEQQHKLDFKAYEQALQYSPYGSTLPASLPLGSASVTTRSPIEPSALEPAYYQGVYSRPVLNTS	GT:AD	93/588(16%);93/588(15.82%)

**Comment by susannasiebert** [comment]
It seems like our parsing reflects the data in the vcf, however it looks like the downstream sequence is incorrect in your vcf for this entry. Has there maybe been a mismatch between build 37 and build 38 when VEP was run? Since the downstream sequence is incorrect there is really nothing we can do on our side. I would try to get in touch with the Ensembl since they are the one that provide the Downstream plugin.

**Comment by susannasiebert** [comment]
The other thing to note here is that there is no difference between the sequence in the DownstreamProtein field and the downstream sequence in the unmutated WildtypeProtein as if the Downstream sequence was not produced with the mutation included. This certainly seems strange but I don't know why that would be.

**Comment by pankajvats** [comment]
i am using ensembl release-84, but i think what i understand from you answer
"protein position (338) and the downstream sequence that is encoded in the CSQ field. We take 9 (in your case) amino acids before the mutation and append the downstream sequence to it"

for the example the 
wt nucleotide seq:AGCGCCAGTGATT**A**CATCCAGTCAGTATTC
wt aa seq:SASD**YIQSVF**
mt nucleotide seq:AGCGCCAGTGATT-CATCCAGTCAGTATTC
mt aa seq should be :SASD**SSSQY**.

the downstream seq should have the effect which was not reflected??

**Comment by susannasiebert** [comment]
We only look at the wildtype amino acid sequence and the downstream amino acid sequence that are encoded in the CSQ field. We do not go back to the nucleotide sequences. As such we do not apply the mutation to the nucleotide sequence and produce the proteinsequence from it. This is what the Downstream sequence plugin is supposed to do when you annotate the vcf with VEP.

What you outlined above is what the Downstream plugin is supposed to do but for some reason it didn't work and that is why there is an incorrect/unmutated protein string in the Downstream field.

The first thing I would do is to take your original (not annotated) vcf and run it through VEP again and then check whether the Downstream field still shows the incorrect sequence. Also, can you make sure that you didn't accidentally make any changes to the Downstream plugin file? Maybe just download the current version from their Github repository?

**Comment by pankajvats** [comment]
ok will try again, 

also i asked before about running IEDB locally are you planing to incorporate local IEDB in pvacseq pkg...?

**Comment by susannasiebert** [comment]
I think this might be related: https://github.com/Ensembl/VEP_plugins/issues/28. It looks like they recently merged in a fix for this issue so it might be worthwhile to download the latest version of the Downstream plugin and see if that fixes this issue.

**Comment by susannasiebert** [comment]
regarding support for standalone IEDB: we are currently working on support for fusions which is our highest priority and we hope to get to implementing support for standalone IEDB after that. It would probably not be until November, though.

**Comment by susannasiebert** [comment]
Since this an problem with VEP and not with pVAC-Seq I will close this issue.
