### ISSUE TITLE
Unexpected behaviour of your tests.

### ISSUE THREAD

**Issue by Akado2009** [griffithlab/pVAC-Seq#216]
Greetings!
First of all, thanks You for your software and especially your tests. But we have faced a problem. We need to execute your tests, depending on the package installed in our system, but in your case you're using package from the folder right next to the test folder.
Secondly, if after cloning your repo into local drive and trying to execute scripts, there seem to be some kind of error. 
When executing all scripts together with:
`python3 -m unittest discover tests`
There is no errors, but if I try to execute:
`python3 -m unittest test_pvacseq.py'
There seems to an error with:
```
...Executing MHC Class I predictions
Converting VCF to TSV
usage: pvacseq convert_vcf [-h] [-g GENE_EXPN_FILE] [-i TRANSCRIPT_EXPN_FILE]
                           [--normal-snvs-coverage-file NORMAL_SNVS_COVERAGE_FILE]
                           [--normal-indels-coverage-file NORMAL_INDELS_COVERAGE_FILE]
                           [--tdna-snvs-coverage-file TDNA_SNVS_COVERAGE_FILE]
                           [--tdna-indels-coverage-file TDNA_INDELS_COVERAGE_FILE]
                           [--trna-snvs-coverage-file TRNA_SNVS_COVERAGE_FILE]
                           [--trna-indels-coverage-file TRNA_INDELS_COVERAGE_FILE]
                           input_file output_file
pvacseq convert_vcf: error: argument -g/--gene-expn-file: can't open 'tests/test_data/pvacseq/genes.fpkm_tracking': [Errno 2] No such file or directory: 'tests/test_data/pvacseq/genes.fpkm_tracking'
E
======================================================================
ERROR: test_pvacseq_pipeline (test_pvacseq.PVACTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/argparse.py", line 1188, in __call__
    self._errors)
FileNotFoundError: [Errno 2] No such file or directory: 'tests/test_data/pvacseq/genes.fpkm_tracking'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/argparse.py", line 2295, in _get_value
    result = type_func(arg_string)
  File "/usr/lib/python3.5/argparse.py", line 1191, in __call__
    raise ArgumentTypeError(message % (string, e))
argparse.ArgumentTypeError: can't open 'tests/test_data/pvacseq/genes.fpkm_tracking': [Errno 2] No such file or directory: 'tests/test_data/pvacseq/genes.fpkm_tracking'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/argparse.py", line 1767, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.5/argparse.py", line 1973, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.5/argparse.py", line 1913, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.5/argparse.py", line 1825, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.5/argparse.py", line 2266, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.5/argparse.py", line 2301, in _get_value
    raise ArgumentError(action, msg)
argparse.ArgumentError: argument -g/--gene-expn-file: can't open 'tests/test_data/pvacseq/genes.fpkm_tracking': [Errno 2] No such file or directory: 'tests/test_data/pvacseq/genes.fpkm_tracking'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/akado2009/Desktop/pVAC-Seq-master/tests/test_pvacseq.py", line 161, in test_pvacseq_pipeline
    '-d', 'full',
  File "/home/akado2009/.local/lib/python3.5/site-packages/pvacseq/lib/main.py", line 252, in main
    pipeline.execute()
  File "/home/akado2009/.local/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 233, in execute
    self.convert_vcf()
  File "/home/akado2009/.local/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 78, in convert_vcf
    lib.convert_vcf.main(convert_params)
  File "/home/akado2009/.local/lib/python3.5/site-packages/pvacseq/lib/convert_vcf.py", line 146, in main
    args = parser.parse_args(args_input)
  File "/usr/lib/python3.5/argparse.py", line 1735, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.5/argparse.py", line 1774, in parse_known_args
    self.error(str(err))
  File "/usr/lib/python3.5/argparse.py", line 2394, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib/python3.5/argparse.py", line 2381, in exit
    _sys.exit(status)
SystemExit: 2

----------------------------------------------------------------------
Ran 4 tests in 2.156s

FAILED (errors=1)

```
Also, there is a fun things. When I'm executing test out of the tests folder, everything works fine, but the I try to execute them within the folder - tests crash on test_pvacseq.py
What should I do in this case?

**Comment by susannasiebert** [comment]
Hi,

Our tests aren't set up to be executed by the user. Internally, we are using them for integration testing to ensure that any code changes made in a GitHub pull requests don't introduce a bug. As such we need to test the code that sits alongside the tests, instead of a local install. Can you give some information as to why you want to execute our integration tests on your local package? If you want to test your local install you could always use the test file and adapt it to your needs.

Regarding the error you posted: are you seeing the same error when you are in the main repository directory (one level up) and try to execute `python3 -m unittest tests/test_pvacseq.py`?

**Comment by Akado2009** [comment]
We're trying at the moment to implement it in the pipeline, maintaining and upgrading it as new releases come. I've already remade it to check a local library, but I'm still getting this, I'd say, 'fancy error'.
it still works, if I try:
`python3 -m unittest test/test_pvacseq.py'
The error is the same for Github version and the local one.

**Comment by susannasiebert** [comment]
The problem is that the `test_data/pvacseq/additional_input_file_list.yaml`  that is referenced in the tests contains relative paths to the additional input files. These paths are relative because we don't know the path for the current repository ahead of time. On our side the tests are always executed from the main repository directory. So you can either run the tests from that location or you have to change the paths in the `test_data/pvacseq/additional_input_file_list.yaml` file to be relative to the location you are using to execute the tests.

**Comment by susannasiebert** [comment]
On second thought I will change it so that the yaml files gets written during test execution with the actual full path to your local files. That should eliminate this error.

**Comment by Akado2009** [comment]
@susannasiebert thanks in advance!

**Comment by susannasiebert** [comment]
The test behavior has been updated in version 4.0.2. Please let me know if I can resolve this issue.

**Comment by Akado2009** [comment]
@susannasiebert Thanks a lot! Yup, you can resolve it.
