### ISSUE TITLE
Allow input VCFs that encode readcount and expression data directly

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVAC-Seq#219]

**Comment by susannasiebert** [comment]
This feature has been added in version 4.0.2.

**Comment by mPiyushkumar** [comment]
Hi,

Is this functionality available in the latest release? 

Cheers,
Piyush

**Comment by susannasiebert** [comment]
No, unfortunately not. It's still on our to-do list.

**Comment by susannasiebert** [comment]
This has been superseded by https://github.com/griffithlab/pVACtools/issues/46
