### ISSUE TITLE
is Score eq ic50

### ISSUE THREAD

**Issue by patidarr** [griffithlab/pVAC-Seq#230]
Hi,

Could you please confirm if the score in the final.tsv file is same as IC50 reported by the tools?

Also how do I add alleles? i.e. using the HLA prediction tools I got a allele x and its not available in the tool as of now, would it be easy to add it to the list so that I can calculate binding against the x allele?

Thanks,
Rajesh

**Comment by susannasiebert** [comment]
Hi Rajesh,

Yes, the scores reported in the final.tsv file are IC50 values.

Unfortunately, it's not possible to add alleles for a prediction algorithm to our tool. We use IEDB under the hood which in turn uses different prediction algorithms. Those are each restricted to a set of alleles which in turn means that pVAC-Seq is restricted by the list of alleles that each prediction algorithm supports. You could try contacting IEDB and see if it's possible for them to add more alleles.

Thanks,
Susanna

**Comment by patidarr** [comment]
Thanks for the information.
I will contact IEDB to see the possibility of adding new alleles. 

I ran netmhcpan on a list of variants for the allele HLA-A*01:01 and got 154 as IC50 but when I ran pVAC-Seq I got a very smaller IC50. is this expected? 
`netmhcpan	HLA-A*01:01	9	FTDTDELQM	**154.781846025**`
![image](https://cloud.githubusercontent.com/assets/4172322/20323111/814a6eca-ab49-11e6-93f8-7b5d6c1e34a4.png)

**Comment by susannasiebert** [comment]
The value reported by pVAC-Seq matches what IEDB reports:
```
curl --data "method=netmhcpan&sequence_text=FTDTDELQM&allele=HLA-A*01:01&length=9" http://tools-api.iedb.org/tools_api/mhci/
allele	seq_num	start	end	length	peptide	ic50	percentile	rank
HLA-A*01:01	1	1	9	9	FTDTDELQM	89.50	0.3
```

Could it be that your local install of NetMHCpan is a different version than the one IEDB uses? As far as I know IEDB uses version 2.8 of NetMHCpan. If this doesn't explain the difference than I would contact IEDB about this problem. pVAC-Seq simply reports the values that IEDB returns.

**Comment by patidarr** [comment]
got it, it's a version issue; when I installed from IEDB_MHC_I-2.5.tar.gz i got netMHCpan-2.3.
Strange with the newer version of IEDB_MHC I got a fairly older version of netmhcpan.

Thanks a lot,
Rajesh

**Comment by susannasiebert** [comment]
That's unexpected. Might be worthwhile to bring this up to IEDB.
