### ISSUE TITLE
Local IEDB Class I: predict_binding.py args error

### ISSUE THREAD

**Issue by serge2016** [griffithlab/pVAC-Seq#232]
Hello.

I'm trying to run pVAC-Seq 4.0.3 with local IEDB Class I installed in Docker container. And when I "log into" the container manually (docker run -ti --entrypoint /bin/bash ...) and execute pVAC-Seq - everything is ok. But when I use simply docker run I get very strange error:
```
[2016-11-21 19:52:11]  Running pVAC-Seq pipeline (len=15) ...
  Running using local IEDB ...
  Command: 'python3 /soft/pvacseq/bin/pvacseq run -e 8 -l 15 --iedb-install-directory /soft/IEDB /output/Test.annot-vep.vcf Test "H-2-Db,H-2-Dd,H-2-Kb,H-2-Kd,H-2-Kk,H-2-Ld" NetMHC /output'.
  PID=372 (last job)
Executing MHC Class I predictions
Converting VCF to TSV
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-64
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Entries 1-128
Completed
Processing entries for Allele H-2-Db and Epitope Length 8 - Entries 1-128
Running IEDB on Allele H-2-Db and Epitope Length 8 with Method NetMHC - Entries 1-128
Usage: predict_binding.py method allele or [options] arg length
---
Following are the available choices - 
   method: ann, comblib_sidney2008, consensus, IEDB_recommended, netmhcpan, smm, smmpmbec, pickpocket, netmhccons
   allele: an allele name
   length: a length

predict_binding.py: error: incorrect number of arguments
Completed
Parsing IEDB Output for Allele H-2-Db and Epitope Length 8 - Entries 1-128
Completed
...
```
Any ideas?

Moreover I'd suggest to check the exit code of `predict_binding.py` and stop pipeline in such cases, printing the command line in the error message.

**Comment by serge2016** [comment]
As I understand, I get this error when use docker run due to `sys.stdin`, which is empty but exists. When I run it manually from terminal everything is ok, and when docker runs it itself, the stdin is taken from _some place_, and it causes the error.

Here is the workaround, I've found:
```
sed -i 's|^\(.*args.append(infile).*\)$|                if infile:\n    \1|' /soft/IEDB/mhc_i/src/predict_binding.py
```

Here is how I figured it out:
```
sed -i 's|^\(.*parser.error("incorrect number of arguments\).*$|\1; args got: {}.".format(args))|' /soft/IEDB/mhc_i/src/predict_binding.py

sed -i 's|^\(.*if args.iedb_executable_path is not None:.*\)$|\1\n        print("Running locally ...")\n        print("args={}".format(args))\n        print("CMD={}".format(prediction_class_object.iedb_executable_params(args)))|' /soft/pvacseq/lib/python3.5/site-packages/pvacseq-4.0.3-py3.5.egg/pvacseq/lib/call_iedb.py
```

**Comment by susannasiebert** [comment]
Can you please put your Dockerfile?

What happens when you explicitly set the ENTRYPOINT in the Dockerfile?

**Comment by susannasiebert** [comment]
You could also try to modify the if clause (`if sys.stdin in select.select([sys.stdin], [], [], 0)[0]`) in predict_binding.py to check the length of sys.stdin. Something like `if sys.stdin and len(sys.stdin) > 0 in select.select([sys.stdin], [], [], 0)[0]`. I didn't test this suggestion so I don't know if this would work.

**Comment by serge2016** [comment]
Dear @susannasiebert 
As I mentioned earlier, it is enough to add `if infile:` before `args.append(infile)`. But I don't know, how to ask the authors of local IEDB script to add this simple `if`...

**Comment by serge2016** [comment]
About Dockerfile. Here it is.
But I also have rather big entrypoint.sh script. Can I send to you by email?
[Dockerfile.zip.txt](https://github.com/griffithlab/pVAC-Seq/files/608128/Dockerfile.zip.txt)

**Comment by susannasiebert** [comment]
Historically, IEDB hasn't been very good about including user-suggested changes like yours in their releases. They also only release every 6 months. You can try submitting a ticket [here](http://help.iedb.org/hc/en-us).

You can email your entrypoint script to pvacseq-support@genome.wustl.edu.

**Comment by susannasiebert** [comment]
Sergey, are you still running into this error? Can I resolve this issue?

**Comment by serge2016** [comment]
Susanna, I've "fixed" it as I described...
Ok, close it)
