### ISSUE TITLE
ERROR: You can only submit one Fasta sequence (IEDB MHC_I updated from 2.15.1 to 2.15.2)

### ISSUE THREAD

**Issue by serge2016** [griffithlab/pVAC-Seq#244]
Hello!
IEDB_MHC_I-2.15.1 is not available any more (it was updated to 2.15.2). After update I've got this:
```
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Entries 1-128
Completed
Processing entries for Allele H-2-Db and Epitope Length 8 - Entries 1-128
Running IEDB on Allele H-2-Db and Epitope Length 8 with Method NetMHC - Entries 1-128
ERROR: You can only submit one Fasta sequence.
Completed
Parsing IEDB Output for Allele H-2-Db and Epitope Length 8 - Entries 1-128
Completed
Processing entries for Allele H-2-Dd and Epitope Length 8 - Entries 1-128
Running IEDB on Allele H-2-Dd and Epitope Length 8 with Method NetMHC - Entries 1-128
ERROR: You can only submit one Fasta sequence.
Completed
Parsing IEDB Output for Allele H-2-Dd and Epitope Length 8 - Entries 1-128
Completed
Processing entries for Allele H-2-Kb and Epitope Length 8 - Entries 1-128
Running IEDB on Allele H-2-Kb and Epitope Length 8 with Method NetMHC - Entries 1-128
ERROR: You can only submit one Fasta sequence.
Completed
Parsing IEDB Output for Allele H-2-Kb and Epitope Length 8 - Entries 1-128
Completed
Processing entries for Allele H-2-Kd and Epitope Length 8 - Entries 1-128
Running IEDB on Allele H-2-Kd and Epitope Length 8 with Method NetMHC - Entries 1-128
ERROR: You can only submit one Fasta sequence.
Completed
Parsing IEDB Output for Allele H-2-Kd and Epitope Length 8 - Entries 1-128
Completed
Processing entries for Allele H-2-Kk and Epitope Length 8 - Entries 1-128
Running IEDB on Allele H-2-Kk and Epitope Length 8 with Method NetMHC - Entries 1-128
ERROR: You can only submit one Fasta sequence.
Completed
Parsing IEDB Output for Allele H-2-Kk and Epitope Length 8 - Entries 1-128
Completed
Processing entries for Allele H-2-Ld and Epitope Length 8 - Entries 1-128
Running IEDB on Allele H-2-Ld and Epitope Length 8 with Method NetMHC - Entries 1-128
ERROR: You can only submit one Fasta sequence.
Completed
Parsing IEDB Output for Allele H-2-Ld and Epitope Length 8 - Entries 1-128
Completed
Combining Parsed IEDB Output Files
Completed
Running Binding Filters
Completed

Done: pvacseq has completed. File /output/MHC_Class_I/Test.final.tsv contains list of filtered putative neoantigens. We recommend appending coverage information and running `pvacseq coverage_filter` to filter based on sequencing coverage information
```
Here we see 2 issues:
1) File IEDB_MHC_I-2.15.2/src/util.py now has:
```
        if len(filter(None, input_sequences)) >= 2:
            sys.stderr.write("ERROR: You can only submit one Fasta sequence.\n")
            exit(1)
```
in `def extract_fasta()` and it is not compatible with fasta-files, generated by pVAC-Seq 4.0.5.
2) pVAC-Seq doesn't stop though an error occurs.

**Comment by susannasiebert** [comment]
Thanks for the bug report. I will look into it.

**Comment by susannasiebert** [comment]
How feasible would it be for you to delete/comment out the check in IEDB_MHC_I-2.15.2/src/util.py? You would also need to delete the line `assert (len(length) == len(proteins.sequences))` in `IEDB_MHC_I-2.15.2/src/predict_binding.py`. 

Fixing pVAC-Seq to provide the new input as required by IEDB would take a good amount of development work since we require at least the wildtype and mutant fasta sequences for a transcript to be submitted in the same IEDB call. Otherwise our downstream parsing won't work. We will basically need to rewrite a good chunk of the pVAC-Seq workflow. As a temporary solution the above code deletions should do the trick, though.

**Comment by serge2016** [comment]
The difference between IEDB_MHC_I-2.15.1 & IEDB_MHC_I-2.15.2:
Folders added:

- data/MHCI_mhcibinding20130222/netmhcstabpan/
- method/netmhcstabpan_1_0_executable/

Files changed:
![iedb_mhc_i_2 15 1_vs_2 15 2](https://cloud.githubusercontent.com/assets/18323865/21449087/9c52263a-c8fa-11e6-8000-aeb55d7ac7a6.png)

**Comment by susannasiebert** [comment]
Great. This change might break IEDB NetMHCstabpan but pVAC-Seq doesn't support NetMHCstabpan currently so it won't matter.

We will be working on restructuring the pVAC-Seq pipeline to work with IEDB without having to modify their codebase to the extend that we are now.

I'm closing this issue for now but feel free to reopen or make a new one should you run into any more problems.
