### ISSUE TITLE
Skip invalid alleles

### ISSUE THREAD

**Issue by patidarr** [griffithlab/pVAC-Seq#245]
Hi,

would it be possible to throw a warning in case of a invalid allele and skip it from computation, rather than error and exit? I am trying to include this in a pipeline and I was hoping whatever alleles I get I don't need to check each of them if they are valid or not and can go through pvacseq without manual interference. 
Here is how I am planning to use the tool:
https://github.com/patidarr/ngs_pipeline/blob/master/ruleBook/NeoAntigen.snakefile

Thanks,
Rajesh

**Comment by susannasiebert** [comment]
Hi Rajesh,

Yes, that change shouldn't be a problem. I will add a "enhancement" label to this issue to mark it as a feature request. 

- Susanna

**Comment by patidarr** [comment]
Thanks!!

**Comment by susannasiebert** [comment]
@patidarr Could you please post the error message that you are receiving in your pipeline? We check the allele in a couple of places and I just want to make sure that I'm deleting the correct checks.

**Comment by patidarr** [comment]
Here is the message I got.
Allele HLA-A*24:0222 not valid. Run `pvacseq valid_alleles` for a list of valid allele names.

**Comment by susannasiebert** [comment]
Ok, PR #253 should fix this.

**Comment by patidarr** [comment]
Thanks,

When would this be available as a release? 

maybe someone already asked for it but how do I give fusions as input? an example input will serve me well.

Thanks,
Rajesh

**Comment by susannasiebert** [comment]
Support for fusions is a work-in-progress but should become available in the next release which is anticipated for later this month. The expected input file would be the output from running the INTEGRATE-Neo pipeline https://github.com/ChrisMaherLab/INTEGRATE-Neo

PR #253 will also be part of the next release.

**Comment by susannasiebert** [comment]
This change is now live as part of the newest version (4.0.6)

**Comment by patidarr** [comment]
Thanks.
