### ISSUE TITLE
Help with running using --iedb-install-directory

### ISSUE THREAD

**Issue by patidarr** [griffithlab/pVAC-Seq#254]
Hi,

We installed IEDB tools and edited the scripts to point to python 2.7 as in readtheDocs but getting following error message
[patidarr@login01 patidarr]$  pvacseq run -e 9 --iedb-install-directory $IEDB_TOOLS  4071-2AFrTu.somatic.vep.vcf CL0062_T1D_EM HLA-A*01:01,HLA-A*29:05,HLA-B*08:01,HLA-C*06:02,HLA-C*07:01 {NNalign,NetMHC,NetMHCIIpan} te
Executing MHC Class I predictions
Converting VCF to TSV
TSV file already exists. Skipping.
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-100
Split TSV file for Entries 1-100 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 101-200
Split TSV file for Entries 101-200 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 201-300
Split TSV file for Entries 201-300 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 301-400
Split TSV file for Entries 301-400 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 401-500
Split TSV file for Entries 401-500 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 501-600
Split TSV file for Entries 501-600 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 601-607
Split TSV file for Entries 601-607 already exists. Skipping.
Completed
Generating Variant Peptide FASTA and Key Files
Split FASTA file for Entries 1-200 already exists. Skipping.
Split FASTA file for Entries 201-400 already exists. Skipping.
Split FASTA file for Entries 401-600 already exists. Skipping.
Split FASTA file for Entries 601-800 already exists. Skipping.
Split FASTA file for Entries 801-1000 already exists. Skipping.
Split FASTA file for Entries 1001-1200 already exists. Skipping.
Split FASTA file for Entries 1201-1214 already exists. Skipping.
Completed
Processing entries for Allele HLA-A*01:01 and Epitope Length 9 - Entries 1-200
IEDB file for Allele HLA-A*01:01 and Epitope Length 9 with Method NetMHC (Entries 1-200) already exists. Skipping.
Parsed Output File for Allele HLA-A*01:01 and Epitope Length 9 (Entries 1-200) already exists. Skipping
Processing entries for Allele HLA-A*29:05 and Epitope Length 9 - Entries 1-200
Allele HLA-A*29:05 not valid for Method NetMHC. Skipping.
Processing entries for Allele HLA-B*08:01 and Epitope Length 9 - Entries 1-200
Running IEDB on Allele HLA-B*08:01 and Epitope Length 9 with Method NetMHC - Entries 1-200
Traceback (most recent call last):
  File "/apps/pVAC-Seq/4.0.2/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/lib/main.py", line 282, in main
    pipeline.execute()
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 253, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 367, in call_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/lib/call_iedb.py", line 51, in main
    response = run(prediction_class_object.iedb_executable_params(args), stdout=PIPE)
  File "/apps/Python/3.5.0/lib/python3.5/subprocess.py", line 696, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/apps/Python/3.5.0/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/apps/Python/3.5.0/lib/python3.5/subprocess.py", line 1540, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'python2.7'

Any clues on how to resolve this would be very helpful.

Thanks,
Rajesh

**Comment by susannasiebert** [comment]
The same error message was reporter in #231 and the user was able to get it to run by installing tcsh `sudo apt-get install tcsh`.

**Comment by patidarr** [comment]
I am still getting some error messages while using local IEDB

my IEDB installation is correct I think...
[patidarr@login01 mhc_i]$ ./src/predict_binding.py netmhcpan -m ./examples/protein_mhc_B0702.fasta 9 ./examples/input_sequence.fasta
allele  length  peptide ic50
User defined    9       MGQIVTMFE       36417.0
User defined    9       GQIVTMFEA       36190.4


but when I run
 pvacseq run -e 8,9,10,11 --iedb-install-directory  /projects/Clinomics/IEDB/ CL0068/20160415/CL0068_T1D_E/NeoAntigen/CL0068_T1D_E.final.vcf CL0068_T1D_E ${allele} {NNalign,NetMHC,NetMHCIIpan,NetMHCcons,NetMHCpan,PickPocket,SMM,SMMPMBEC,SMMalign} CL0068/20160415/CL0068_T1D_E/NeoAntigen1/

I am getting following:
Executing MHC Class I predictions
Converting VCF to TSV
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-100
Splitting TSV into smaller chunks - Entries 101-200
Splitting TSV into smaller chunks - Entries 201-300
Splitting TSV into smaller chunks - Entries 301-394
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Entries 1-200
Generating Variant Peptide FASTA and Key Files - Entries 201-400
Generating Variant Peptide FASTA and Key Files - Entries 401-600
Generating Variant Peptide FASTA and Key Files - Entries 601-788
Completed
Processing entries for Allele HLA-A*02:01 and Epitope Length 8 - Entries 1-200
Running IEDB on Allele HLA-A*02:01 and Epitope Length 8 with Method NetMHC - Entries 1-200
Traceback (most recent call last):
  File "/projects/Clinomics/IEDB/mhc_i/src/predict_binding.py", line 378, in <module>
    Prediction().main()
  File "/projects/Clinomics/IEDB/mhc_i/src/predict_binding.py", line 370, in main
    self.commandline_input(args)
  File "/projects/Clinomics/IEDB/mhc_i/src/predict_binding.py", line 72, in commandline_input
    mhc_predictor = MHCBindingPredictions(input)
  File "/projects/Clinomics/IEDB/mhc_i/src/seqpredictor.py", line 965, in __init__
    self.tool_selection.extend(ps.get_tool_selection(self.method, m, l, self.tool))
  File "/projects/Clinomics/IEDB/mhc_i/src/util.py", line 180, in get_tool_selection
    allele_list = miad.get_allele_names_for_method(method_name=pred_method.replace('IEDB_', ''))
  File "/projects/Clinomics/IEDB/mhc_i/allele_info/allele_info.py", line 32, in wrapped_func
    ret = func(*args, **kwargs)
  File "/projects/Clinomics/IEDB/mhc_i/allele_info/allele_info.py", line 121, in get_allele_names_for_method
    cur.execute(sql, where_args)
sqlite3.OperationalError: disk I/O error
Completed

**Comment by susannasiebert** [comment]
This error is coming from inside IEDB. I personally haven't encountered it before. I suggest putting in a ticket with IEDB as they will probably have a clearer idea of what this error means.

**Comment by patidarr** [comment]
Sure I can file a ticket with them, any idea on what commands are evoked  by pvacseq? I can try to run them on command line to check whether I can reproduce the error or not.

**Comment by susannasiebert** [comment]
The command issued by pVAC-Seq looks like this: `python2.7 /projects/Clinomics/IEDB/mhc_i/src/predict_binding.py ann HLA-A\*02:01 8 <input fasta>`. Try executing that from inside your Python 3.5 Conda environment and see if you reproduce the error.

**Comment by patidarr** [comment]
yes,
I am getting the same error with this command, I contacted IEDB regarding this.

Thanks for the help.
Rajesh

**Comment by patidarr** [comment]
Hi,

I finally got the IEDB tools installed correctly on the server but getting following error now.

Completed
Parsing IEDB Output for Allele HLA-A*02:01 and Epitope Length 8 - Entries 1-50
Traceback (most recent call last):
  File "/apps/pVAC-Seq/4.0.6/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/lib/main.py", line 285, in main
    pipeline.execute()
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 253, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 391, in call_iedb_and_parse_outputs
    lib.parse_output.main(params)
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 453, in main
    iedb_results = process_input_iedb_file(args.input_iedb_files, tsv_entries, args.key_file, args.top_result_per_mutation, args.top_score_metric)
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 364, in process_input_iedb_file
    iedb_results              = parse_iedb_file(input_iedb_files, tsv_entries, key_file)
  File "/apps/Python/3.5.0/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 230, in parse_iedb_file
    protein_label  = int(line['seq_num'])
KeyError: 'seq_num'


Here is my command line
 pvacseq run -e 8,9,10,11 --iedb-install-directory /tmp --fasta-size=50 CL0068/20160415/CL0068_T1D_E/NeoAntigen/CL0068_T1D_E.final.vcf CL0068_T1D_E ${allele} {NNalign,NetMHC,NetMHCIIpan,NetMHCcons,NetMHCpan,PickPocket,SMM,SMMPMBEC,SMMalign} CL0068/20160415/CL0068_T1D_E/NeoAntigen/

**Comment by susannasiebert** [comment]
It looks like the output files from IEDB are not as expected for at least one of the prediction algorithms. I will need to investigate further to find out what changed about the IEDB output files.

**Comment by susannasiebert** [comment]
Could you tell me if any of these files are empty in your output directory:

`MHC_Class_I/tmp/CL0068_T1D_E.*.HLA-A\*02:01.8.tsv_1-50`
`MHC_Class_II/tmp/CL0068_T1D_E.*.HLA-A\*02:01.8.tsv_1-50`

The first `*` is a placeholder for the prediction algorithm.

**Comment by patidarr** [comment]
`[patidarr@tghighmem-01 ProcessedResults]$ wc CL0068/20160415/CL0068_T1D_E/NeoAntigen/MHC_Class_I/tmp/CL0068_T1D_E.*.HLA-A\*02:01.8.tsv_1-50
    1 CL0068/20160415/CL0068_T1D_E/NeoAntigen/MHC_Class_I/tmp/CL0068_T1D_E.ann.HLA-A*02:01.8.tsv_1-50
    1 CL0068/20160415/CL0068_T1D_E/NeoAntigen/MHC_Class_I/tmp/CL0068_T1D_E.netmhccons.HLA-A*02:01.8.tsv_1-50
  253 CL0068/20160415/CL0068_T1D_E/NeoAntigen/MHC_Class_I/tmp/CL0068_T1D_E.netmhcpan.HLA-A*02:01.8.tsv_1-50
    1 CL0068/20160415/CL0068_T1D_E/NeoAntigen/MHC_Class_I/tmp/CL0068_T1D_E.pickpocket.HLA-A*02:01.8.tsv_1-50
  253 CL0068/20160415/CL0068_T1D_E/NeoAntigen/MHC_Class_I/tmp/CL0068_T1D_E.smm.HLA-A*02:01.8.tsv_1-50
  253 CL0068/20160415/CL0068_T1D_E/NeoAntigen/MHC_Class_I/tmp/CL0068_T1D_E.smmpmbec.HLA-A*02:01.8.tsv_1-50
`

All of them have at least 1 line.

**Comment by susannasiebert** [comment]
Can you please check one of the files with 1 line and see what the contents are? Is it an empty line? Is it just a header line?

**Comment by patidarr** [comment]
`[patidarr@tghighmem-01 NeoAntigen]$ cat MHC_Class_I/tmp/CL0068_T1D_E.ann.HLA-A\*02\:01.8.tsv_1-50
Could not find tools matching species='None', allele='HLA A*0201', length='8', method='ann'
[patidarr@tghighmem-01 NeoAntigen]$ cat MHC_Class_I/tmp/CL0068_T1D_E.netmhccons.HLA-A\*02\:01.8.tsv_1-50
Selected prediction method 'netmhccons' does not exist
[patidarr@tghighmem-01 NeoAntigen]$ cat MHC_Class_I/tmp/CL0068_T1D_E.pickpocket.HLA-A\*02\:01.8.tsv_1-50
Selected prediction method 'pickpocket' does not exist
[patidarr@tghighmem-01 NeoAntigen]$
`


I am using IEDB_MHC_I-2.5.tar.gz

**Comment by susannasiebert** [comment]
Thank you for posting the contents of these files. If you are really running IEDB_MHC_I-2.5.tar.gz it might be the case that that version did not support pickpocket, netmhccons, and ann (netmhc) yet. 2.5 is from 2011 and the latest version is 2.15.3. You might want to consider updating to the newest IEDB version. If you are not able to update to the newest version you would need to remove these methods from your command.

**Comment by patidarr** [comment]
Got it. I will install the newer version.

Thanks a lot.

**Comment by venkataddala** [comment]
Hey guys, Have you seen any error like below with recent IEDB, MHC-1 - 2.15.3 and MHC-II 2.16, when you are using Pickpocket or NetMHCcons,

SError: [Errno 13] Permission denied: '/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/data/MHCI_mhcibinding20130222/pickpocketBRyLvOinput'

OSError: [Errno 13] Permission denied: '/software/IEDB_MHC/IEDB_MHC-20170201/mhc_i/data/MHCI_mhcibinding20130222/netmhcconsea2TSFinput'

**Comment by susannasiebert** [comment]
I have not. What are the permissions on this file/directory? Can you change the permissions?

**Comment by patidarr** [comment]
I noticed this as well, even though my admin changed the scratch dir in configure I got this error message. finally I ended up installing IEDB tools to public area and then it worked.

**Comment by venkataddala** [comment]
Thanks Guys.!!
