### ISSUE TITLE
can I use TPM instead of FPKM

### ISSUE THREAD

**Issue by patidarr** [griffithlab/pVAC-Seq#256]
Hi,

We use TPM (edgeR), would it be possible to take this as input instead of cufflinks output?

Thanks,
Rajesh

**Comment by susannasiebert** [comment]
This would require some development work on our side. We have added it to our list of features to add in the future but it's not clear when we would be able to get to it.

**Comment by susannasiebert** [comment]
@patidarr We are transitioning the pVACseq issue tracking to the [pVACtools repository](https://github.com/griffithlab/pVACtools). Issue tracking for this feature addition will happen at https://github.com/griffithlab/pVACtools/issues/46.
