### ISSUE TITLE
ERROR: VCF file contains more than one sample

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVAC-Seq#257]
Hi Guys,

I'm trying many ways to run pVAC (4.0.5) on my samples., I'm facing lot or errors while running, some like:

File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/convert_vcf.py", line 48, in parse_csq_format
    if info_fields['CSQ'] is None:
KeyError: 'CSQ'

OR

ERROR: VCF file contains more than one sample
 
I'm attaching VCF file which i used, and pVAC command,

VCF File : https://drive.google.com/open?id=0B8EP7wx5peEkd3R1OFQtRnlRdDg

pvacseq run --iedb-install-directory /software/IEDB_MHC/IEDB_MHC-2.15.1 -e 8,9,10,11 ../VEP/2854_vep.vcf MELA_2854 HLA-A*24:02 NetMHC NetMHCpan ../pVACoutput/
 
please check the file and help me out.

**Comment by chrisamiller** [comment]
That's a pretty straightforward error - your VCF file indeed has more than one sample: It has columns for "NORMAL" and "TUMOR".  You need a VCF with just the "TUMOR" column.

**Comment by venkataddala** [comment]
Hi Chris,
Well.. that's the error, Can you try VCF with only TUMOR column. It will through 

File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/convert_vcf.py", line 48, in parse_csq_format
if info_fields['CSQ'] is None: 
          KeyError: 'CSQ

**Comment by chrisamiller** [comment]
Are you removing the TUMOR field before or after annotating with VEP?  My guess is that you probably have to do the former, as the vep annotations may no longer match up.  See if that helps

**Comment by venkataddala** [comment]
I removed TUMOR filed from varscan VCF and annotated with VEP with the specs needed for pvac-seq. I'm still facing this error,
File "/software/python/Python-3.5.0/lib/python3.5/site-packages/pvacseq/lib/convert_vcf.py", line 48, in parse_csq_format
if info_fields['CSQ'] is None:
KeyError: 'CSQ

**Comment by venkataddala** [comment]
Resolved this issue. used VEP filter and --pick option.

**Comment by xuxue1986** [comment]
Hi , whether you mean :perl /path/to/vep --cache -i input.vcf -o outpu.VEP.vcf --format vcf --force_overwrite  --pick ?
