### ISSUE TITLE
Understanding Fold Change

### ISSUE THREAD

**Issue by patidarr** [griffithlab/pVAC-Seq#259]
Hi,

I thought the idea of running new-antigen prediction is to know if the HLA binding to MT is better then WT or not. Wouldn't having Fold change in that direction be more helpful? 
Or I am missing something very important here..

Thanks,
Rajesh

**Comment by susannasiebert** [comment]
The Fold Change represents the rate of decrease in the binding affinity. If the the WT was 900 and the MT was 300 the Fold Change would be 3 which is 3 fold decrease.

**Comment by patidarr** [comment]
Got it, Is it possible to add it as "increase in binding affinity" ? For tumor samples we are mostly interested in increase in binding affinity and I noticed some of my best MT binders are filtered out because binding to WT was very very low compared to MT. 
if its too much I can always parse the .combined.parse.tsv to get the results I am interested in.

**Comment by chrisamiller** [comment]
Just to make sure we're on the same page here: binding affinity is an inverse measure - that is, lower ic50 score means better binding. So if WT is lower than MT, that means the WT is a better binder.

**Comment by patidarr** [comment]
Now we are.
