### ISSUE TITLE
Peptides in output TSV file are not sorted in any way.

### ISSUE THREAD

**Issue by Akado2009** [griffithlab/pVAC-Seq#261]
Greetings, colleagues,

it is said that pVAC-Seq usually sorts output peptides by score, but as it can be seen from the example below it doesnt. Is it that we are missing any input parameter or its just the way the program is working?
[pvacseq_pvacseq_output_tsv.tsv.zip](https://github.com/griffithlab/pVAC-Seq/files/756722/pvacseq_pvacseq_output_tsv.tsv.zip)

**Comment by susannasiebert** [comment]
Unfortunately, since we are splitting up the calls to IEDB by allele, method, epitope lengths, and fasta chunks, there is only sorting within each processing set. We don't sort the overall results file. I will add this as a feature request as this is certainly not ideal.

**Comment by susannasiebert** [comment]
The latest version of pVAC-Seq (4.0.7) added improved sorting of the output file. The report is now sorted by “Gene Name” and “Mutation” and within these categories by the MT score - either “Median MT Score” or “Best MT score” depending on the top-score-metric used.
