### ISSUE TITLE
KeyError: '-4'

### ISSUE THREAD

**Issue by katharineqn** [griffithlab/pVAC-Seq#268]
Hi,

I have a problem when I'm running pvacseq to predict peptides. Please help.

pvacseq run ./datapre/pVAC-Seq/vcf_new/sample1.mut2_PON_nsd_addindel_sp.neo.vcf sample1 DRB1*04:03,DRB1*15:02 NetMHCIIpan ./tmp/pVAC-Seq-2/sample1/DRB -m lowest -b 500 -e 8 

Error

Executing MHC Class II predictions
Converting VCF to TSV
TSV file already exists. Skipping.
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-100
Split TSV file for Entries 1-100 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 101-200
Split TSV file for Entries 101-200 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 201-300
Split TSV file for Entries 201-300 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 301-400
Split TSV file for Entries 301-400 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 401-500
Split TSV file for Entries 401-500 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 501-600
Split TSV file for Entries 501-600 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 601-700
Split TSV file for Entries 601-700 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 701-800
Split TSV file for Entries 701-800 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 801-900
Split TSV file for Entries 801-900 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 901-1000
Split TSV file for Entries 901-1000 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 1001-1100
Split TSV file for Entries 1001-1100 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 1101-1200
Split TSV file for Entries 1101-1200 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 1201-1300
Split TSV file for Entries 1201-1300 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 1301-1400
Split TSV file for Entries 1301-1400 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 1401-1500
Split TSV file for Entries 1401-1500 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 1501-1600
Split TSV file for Entries 1501-1600 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 1601-1700
Split TSV file for Entries 1601-1700 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 1701-1800
Split TSV file for Entries 1701-1800 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 1801-1900
Split TSV file for Entries 1801-1900 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 1901-2000
Split TSV file for Entries 1901-2000 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 2001-2003
Split TSV file for Entries 2001-2003 already exists. Skipping.
Completed
Generating Variant Peptide FASTA and Key Files
Split FASTA file for Entries 1-200 already exists. Skipping.
Split FASTA file for Entries 201-400 already exists. Skipping.
Split FASTA file for Entries 401-600 already exists. Skipping.
Split FASTA file for Entries 601-800 already exists. Skipping.
Split FASTA file for Entries 801-1000 already exists. Skipping.
Split FASTA file for Entries 1001-1200 already exists. Skipping.
Split FASTA file for Entries 1201-1400 already exists. Skipping.
Split FASTA file for Entries 1401-1600 already exists. Skipping.
Split FASTA file for Entries 1601-1800 already exists. Skipping.
Split FASTA file for Entries 1801-2000 already exists. Skipping.
Split FASTA file for Entries 2001-2200 already exists. Skipping.
Split FASTA file for Entries 2201-2400 already exists. Skipping.
Split FASTA file for Entries 2401-2600 already exists. Skipping.
Split FASTA file for Entries 2601-2800 already exists. Skipping.
Split FASTA file for Entries 2801-3000 already exists. Skipping.
Split FASTA file for Entries 3001-3200 already exists. Skipping.
Split FASTA file for Entries 3201-3400 already exists. Skipping.
Split FASTA file for Entries 3401-3600 already exists. Skipping.
Split FASTA file for Entries 3601-3800 already exists. Skipping.
Split FASTA file for Entries 3801-4000 already exists. Skipping.
Split FASTA file for Entries 4001-4006 already exists. Skipping.
Completed
Processing entries for Allele DRB1*04:03 - Entries 1-200
IEDB file for Allele DRB1*04:03 with Method NetMHCIIpan (Entries 1-200) already exists. Skipping.
Parsing IEDB Output for Allele DRB1*04:03 - Entries 1-200
Traceback (most recent call last):
  File "/data/public/opt/pyenv/versions/anaconda-4.0.0/envs/HLA_typing/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/data/public/opt/pyenv/versions/anaconda-4.0.0/envs/HLA_typing/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/data/public/opt/pyenv/versions/anaconda-4.0.0/envs/HLA_typing/lib/python3.5/site-packages/pvacseq/lib/main.py", line 304, in main
    pipeline.execute()
  File "/data/public/opt/pyenv/versions/anaconda-4.0.0/envs/HLA_typing/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 253, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/data/public/opt/pyenv/versions/anaconda-4.0.0/envs/HLA_typing/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 479, in call_iedb_and_parse_outputs
    lib.parse_output.main(params)
  File "/data/public/opt/pyenv/versions/anaconda-4.0.0/envs/HLA_typing/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 453, in main
    iedb_results = process_input_iedb_file(args.input_iedb_files, tsv_entries, args.key_file, args.top_result_per_mutation, args.top_score_metric)
  File "/data/public/opt/pyenv/versions/anaconda-4.0.0/envs/HLA_typing/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 364, in process_input_iedb_file
    iedb_results              = parse_iedb_file(input_iedb_files, tsv_entries, key_file)
  File "/data/public/opt/pyenv/versions/anaconda-4.0.0/envs/HLA_typing/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 270, in parse_iedb_file
    return match_wildtype_and_mutant_entries(iedb_results, wt_iedb_results)
  File "/data/public/opt/pyenv/versions/anaconda-4.0.0/envs/HLA_typing/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 213, in match_wildtype_and_mutant_entries
    match_wildtype_and_mutant_entry_for_missense(result, mt_position, wt_results)
  File "/data/public/opt/pyenv/versions/anaconda-4.0.0/envs/HLA_typing/lib/python3.5/site-packages/pvacseq/lib/parse_output.py", line 55, in match_wildtype_and_mutant_entry_for_missense
    result['wt_epitope_seq']    = wt_results[match_position]['wt_epitope_seq']
KeyError: '-4'

**Comment by susannasiebert** [comment]
It looks like IEDB changed how the start and end positions are calculated for Class II predictions. A fix for this issue is in PR #264 and will be part of the next release.

**Comment by susannasiebert** [comment]
The newest release (4.0.7) fixes this issue. Please upgrade your install of pVAC-Seq and let me know if you are able to run your data successfully.

**Comment by katharineqn** [comment]
I'm sorry for the low efficiency, and I have not finished the analysis of one sample for over three days.

**Comment by susannasiebert** [comment]
I would recommend that you use a local IEDB install if your analysis takes this long. IEDB asked us to implement a wait time of 60 seconds between each individual call to their API. Some of the slowness you are seeing probably has to do with that. When using the standalone tools, the calls will be execute without wait and will be much faster.
