### ISSUE TITLE
4.0.6: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by kylec** [griffithlab/pVAC-Seq#271]
I'm running 4.0.6 but getting a NoneType not subscriptable error. Attached is my vcf file.
pvacseq run EBL13-EBL14.vep.vcf EBL13 HLA-A*01:01,HLA-A*01:01,HLA-B*08:01,HLA-B*57:01,HLA-C*06:02,HLA-C*07:01, NetMHC EBL13-result -e 8,9,10,11
[EBL13.zip](https://github.com/griffithlab/pVAC-Seq/files/790907/EBL13.zip)

**Comment by susannasiebert** [comment]
@kylec Thanks for the bug report. I will have a look.

**Comment by susannasiebert** [comment]
I believe that the error you are seeing has the same cause as #269. Please try to rerun with an empty output directory. Once you get past the NoneType error you will also get the same IEDB error "ERROR: Input sequence is too short!". I will let you know once we made a new release.

**Comment by kylec** [comment]
i cleared the directory and got "ERROR:  Input sequence is too short!" . Is this a problem with netMHC?

**Comment by susannasiebert** [comment]
See my reply from a couple of days ago. Yes, this is a bug with pVAC-Seq and will be fixed in the next release.
