### ISSUE TITLE
En error: number of arguments

### ISSUE THREAD

**Issue by phil-gusev** [griffithlab/pVAC-Seq#277]
Usage: predict_binding.py method allele or [options] arg length
---
Following are the available choices - 
   method: ann, comblib_sidney2008, consensus, IEDB_recommended, netmhcpan, smm, smmpmbec, pickpocket, netmhccons, netmhcstabpan
   allele: an allele name
   length: a length

predict_binding.py: error: incorrect number of arguments
Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.5/dist-packages/pvacseq/lib/main.py", line 285, in main
    pipeline.execute()
  File "/usr/local/lib/python3.5/dist-packages/pvacseq/lib/pipeline.py", line 253, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/usr/local/lib/python3.5/dist-packages/pvacseq/lib/pipeline.py", line 367, in call_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/usr/local/lib/python3.5/dist-packages/pvacseq/lib/call_iedb.py", line 51, in main
    response = run(prediction_class_object.iedb_executable_params(args), stdout=PIPE, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python2.7', '/home/phil/IEDB/mhc_i/src/predict_binding.py', 'ann', 'HLA-A*01:01', '8', '/home/phil/FL/PVACSEQ_OUT/MHC_Class_I/tmp/test21.fa.split_1-200']' returned non-zero exit status 2

I've printed arguments that had passed to predict_binding.py : ['ann', 'HLA-A*01:01', '8', '/home/phil/FL/PVACSEQ_OUT/MHC_Class_I/tmp/test21.fa.split_1-200', '']
So there somehow an empty string present in the end as an argument. What should I do?

**Comment by susannasiebert** [comment]
A different user ran into this same error in issue #232 when running pVAC-Seq in Docker. He was able to work around it by modifying the IEDB script. His changes can be found in #232. I'm not sure if this workaround would work in your case as well but it's worth a try. I don't think there is much we can do on our end to prevent this error from happening as it seems to be related to how IEDB handles stdin.

**Comment by snashraf** [comment]
I am getting the same error while running  PVAC-Seq2 in docker. is his fix still working?

**Comment by susannasiebert** [comment]
@snashraf can you please post an issue to the https://github.com/griffithlab/pVACtools repository and post your pVACseq command as well as the error message you are getting? This repository here is deprecated and no longer maintained.
