### ISSUE TITLE
Differences in Sub-peptide Position

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVAC-Seq#283]
From: Weixuan Fu <weixuanf@mail.med.upenn.edu>

Dear Jasreet and pVAC-Seq support term,

Thank you for good online documentation and detailed information about pVAC-seq manuscript published in Genome Medicine.

I have set up pVAC-Seq in our HPC environment and ran some tests using data from MEL-69.

Most of columns for a variants were consistent with a previous output from pVAC-Seq pipeline (Order Number: R16-3550). But I found some differences in the column named "Sub-peptide Position". The number in the column is less (-2) in our tests for the same variant with the same MT Epitope Seq. I attached two Excel file with highlighted the difference in Sub-peptide Position. (Result in our test: HLA-A2_example_pVAC-seq_4.0.8_030717.xlsx; Result in Order R16-3550: H_LX-WU_MEL_69.final.120716_unfiltered_partial_result.xlsx). I also attached the the input VCF file (example_MEL_69.vcf) to reproduce the result with the command:

    pvacseq run -e 8,9,10,11 --iedb-install-directory /project/ibilab/tools/IEDB -t example_MEL_69.vcf example_0307 HLA-A*02:01 {NetMHC,NetMHCpan,PickPocket,SMM,SMMPMBEC} HLA-A2_example_pVAC-seq_4.0.8_030717

I am not sure if the difference is from the version of pVAC-seq (the latest version 4.0.8) I used or due to the version of IEDB (IEDB_MHC_I-2.15.3 instead of IEDB_MHC_I-2.15.2 in the online documentation) or wrong parameter setting. Please let me know if you have any suggestions for runing pVAC-seq pipeline.

The rest of inconsistency in the test example is maybe due to the variant annotation using VEP. Below is the command for VEP following the online documentation (http://pvac-seq.readthedocs.io/en/v4.0.8/prerequisites.html) with a extra output filter (--per_gene) and local cache (consistency with port 3337). I also I used latest annotation of hg19 for VEP. Please let me know if you have any suggestions for this part.

    variant_effect_predictor.pl --input_file [INPUT_FILE] --format vcf --output_file [OUTPUT_FILE] --vcf --symbol --per_gene --terms SO --plugin Downstream --plugin Wildtype --dir_plugins [PLUGINS_DIR] --cache --dir_cache [CACHE_DIR] --port 3337

Thank you and best regards,

Weixuan

**Comment by susannasiebert** [comment]
From: Susanna Kiwala <ssiebert@wustl.edu>

Hi Weixuan,

I know that IEDB changed their output for Class II predictions recently, specifically the positions that they return. We made some changes to pVAC-Seq to account for this but it might be that we are still not doing quite the right thing. If you could send us the other output files that pVAC-Seq produced for these runs, it would help us in determining what is going on, especially if they include the tmp folders.

As far as the additional variants that you are seeing in the most recent output, this might be due to filtering. You might want to look at the combined output file from your first run and find the missing peptides and see what scores were returned for them.

Can you tell me what version of pVAC-Seq you used for the earlier run. I don't know what the order number means.

Thanks,

Susanna

**Comment by susannasiebert** [comment]
Weixuan Fu <weixuanf@mail.med.upenn.edu>

Hi Susanna,

Thank you for the super-quick reply.

I think the result in this example is based on MHC Class I predictions. I just add '-k' in the command line for keeping tmp file and attached the zipped result folder herein.

I did not get much information for the first run in the WU. The order number maybe just a sequencing order number. I got these BAM files from David (dspencer@wustl.edu) and I C.c him in this email for more details about which version of pVAC-Seq in the first run.

Thanks,

Weixuan

Hi David,

Could you please let us know which version of pVAC-Seq in the first run over the MEL 69 samples?

Thanks,

Weixuan

**Comment by susannasiebert** [comment]
From: Spencer, David <dspencer@wustl.edu>

Weixuan,


Mike McClellan (cc'ed here) processed the Mel 69 sample. 


Mike, can you tell us what version of pvac-seq you ran on these data?


Thanks,


Dave

**Comment by susannasiebert** [comment]
I looked at the tmp file from the current run and the subpeptide positions are correct compared to the fasta file so IEDB is doing the correct thing. I know we made some changed to how we calculate the fasta sequences so it could be that we are now extracting a longer sequence than previously which would shift the positions around since those are relative to the full fasta sequence that is getting fed to IEDB. But without seeing all the output files from the first run it would be hard to tell whether this is what is happening.

**Comment by weixuanfu2016** [comment]
Great, thank you for quickly checking that!

**Comment by weixuanfu2016** [comment]
From Mike McLellan <mmclella@wustl.edu>

I believe the version I ran on 6 December 2016 was:  v4.0.3

It appears I grabbed the update on 2016-11-17 based on the timestamp.

http://pvac-seq.readthedocs.io/en/v4.0.3/

The original output was modified slightly (position/indel alleles) to generate readcounts. 

Both files are here:

/gscmnt/gc6134/cancer-genomics/medseq/shared/Spencer_David/MEL69/Process/H_LX-WU_MEL_69/epitope_output/MHC_Class_I/

Original output: H_LX-WU_MEL_69.final.tsv

Modified output to generate readcounts: H_LX-WU_MEL_69.final.reformat.tsv
Corresponds to  H_LX-WU_MEL_69.final.120716_unfiltered_partial_result.xlsx

Best,

-Mike M.

**Comment by susannasiebert** [comment]
I reran the data using pVAC-Seq 4.0.3 a local IEDB installation (2.15.3) and I'm not able to replicate the differences in sub-peptide positions. I conclude that it has something to do with different versions of IEDB being used.

**Comment by susannasiebert** [comment]
As I side not, I think 2.15 and 2.15.2 of IEDB where a bit buggy so I wouldn't be surprised if there were some differences in the outputs between these version and 2.15.3.

**Comment by weixuanfu2016** [comment]
Thank you for checking into it. It is good to know the reason of the issue.

**Comment by susannasiebert** [comment]
I will resolve this issue but feel free to make a new issue with any problems you might run into in the future.
