### ISSUE TITLE
Is it possible to add sample_name in the final file. ?  

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVAC-Seq#285]
I am trying to do group analysis for large number of predicted neoantigens, is this possible to add sample_name column in final file?

**Comment by susannasiebert** [comment]
Yes, that shouldn't be a problem. I will make a note to add this feature to the next releases.

**Comment by susannasiebert** [comment]
This feature was added in version 4.0.9. To use it, simply add the  `--additional-report-columns sample_name` option to your pvacseq run command.
