### ISSUE TITLE
DNP not handled correctly

### ISSUE THREAD

**Issue by chrisamiller** [griffithlab/pVAC-Seq#286]
This may be a variation on the previous issue here, where pvacseq doesn't know how to properly parse a complex variant. This one is a DNP:

`11      101127948       .       GG      AA      .       .       CSQ=AA|missense_variant|MODERATE|PGR|ENSG00000082175|Transcript|ENST00000325455|protein_coding|1/8||||2576-2577|1122-1123|374-375|YP/YS|taCCct/taTTct|||-1||HGNC|HGNC:8910|||MTELKAKGPRAPHVAGGPPSPEVGSPLLCRPAAGPFPGSQTSDTLPEVSAIPISLDGLLFPRPCQGQDPSDEKTQDQQSLSDVEGAYSRAEATRGAGGSSSSPPEKDSGLLDSVLDTLLAPSGPGQSQPSPPACEVTSSWCLFGPELPEDPPAAPATQRVLSPLMSRSGCKVGDSSGTAAAHKVLPRGLSPARQLLLPASESPHWSGAPVKPSPQAAAVEVEEEDGSESEESAGPLLKGKPRALGGAAAGGGAAAVPPGAAAGGVALVPKEDSRFSAPRVALVEQDAPMAPGRSPLATTVMDFIHVPILPLNHALLAARTRQLLEDESYDGGAGAASAFAPPRSSPCASSTPVAVGDFPDCAYPPDAEPKDDAYPLYSDFQPPALKIKEEEEGAEASARSPRSYLVAGANPAAFPDFPLGPPPPLPPRATPSRPGEAAVTAAPASASVSSASSSGSTLECILYKAEGAPPQQGPFAPPPCKAPGASGCLLPRDGLPSTSASAAAAGAAPALYPALGLNGLPQLGYQAAVLKEGLPQVYPPYLNYLRPDSEASQSPQYSFESLPQKICLICGDEASGCHYGVLTCGSCKVFFKRAMEGQHNYLCAGRNDCIVDKIRRKNCPACRLRKCCQAGMVLGGRKFKKFNKVRVVRALDAVALPQPVGVPNESQALSQRFTFSPGQDIQLIPPLINLLMSIEPDVIYAGHDNTKPDTSSSLLTSLNQLGERQLLSVVKWSKSLPGFRNLHIDDQITLIQYSWMSLMVFGLGWRSYKHVSGQMLYFAPDLILNEQRMKESSFYSLCLTMWQIPQEFVKLQVSQEEFLCMKVLLLLNTIPLEGLRSQTQFEEMRSSYIRELIKAIGLRQKGVVSSSQRFYQLTKLLDNLHDLVKQLHLYCLNTFIQSRALSVEFPEMMSEVIAAQLPKILAGMVKPLLFHKK      GT:IGT:DP:DP4:BCOUNT:GQ:JGQ:VAQ:BQ:MQ:AMQ:SS:SSC:FT:FA:AD:FDP:SDP:SUBDP:AU:CU:GU:TU:TLOD        0/1:0/1:386:128,138,41,49:95,0,290,0:99:.:228:37,36:60:60,60:2:225:PASS:0.5:287,90:7:0:0:90,95:1,1:287,290:1,1:132.569`

Here are the params/error:

```
$ pvacseq run -b 500 -c 1 -e 8,9,10,11 --iedb-install-directory /Users/cmiller/src/ zz.vcf zz "HLA-A*02:01,HLA-A*68:01,HLA-B*15:07,HLA-B*44:02,HLA-C*03:03,HLA-C*07:04" {NetMHC,NetMHCpan,PickPocket,SMM,SMMPMBEC} zz.out
Executing MHC Class I predictions
Converting VCF to TSV
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-1
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Entries 1-2
Traceback (most recent call last):
  File "/Users/cmiller/anaconda/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/Users/cmiller/anaconda/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/Users/cmiller/anaconda/lib/python3.5/site-packages/pvacseq/lib/main.py", line 285, in main
    pipeline.execute()
  File "/Users/cmiller/anaconda/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 255, in execute
    self.generate_fasta(chunks)
  File "/Users/cmiller/anaconda/lib/python3.5/site-packages/pvacseq/lib/pipeline.py", line 331, in generate_fasta
    lib.generate_fasta.main(generate_fasta_params)
  File "/Users/cmiller/anaconda/lib/python3.5/site-packages/pvacseq/lib/generate_fasta.py", line 103, in main
    position = int(line['protein_position']) - 1
ValueError: invalid literal for int() with base 10: '374-375'

```

Internally, I dropped a one-line VCF file for reproducing the error here:
`/gscuser/cmiller/zz.vcf`

**Comment by susannasiebert** [comment]
Do you happen to still have the tmp directory for this failed run?

**Comment by chrisamiller** [comment]
Yep - moved it to ~cmiller/zz.out/

**Comment by chrisamiller** [comment]
Tested the fix and it appears to work in the hotfix version - thanks!
