### ISSUE TITLE
Add support for multiple versions of NetMHC

### ISSUE THREAD

**Issue by jasonwalker80** [griffithlab/pVAC-Seq#29]
Please see PR #13 for an example of supporting NetMHC 4.0.

**Comment by serge2016** [comment]
Hello! When are you going to add the support of NetMHC v4.0?
If not, then provide the exact working version (link), please.

**Comment by iskandr** [comment]
I'm not sure if this helps, but we've wrapped the NetMHC family of predictors with a uniform API at https://github.com/hammerlab/mhctools. We can add a commandline script for mhctools if you don't want to add another programming language to the pipeline.

**Comment by jasonwalker80** [comment]
As mentioned in #107:
"pvacseq 3.0.0 will make REST API calls to IEDB instead of using local installs. IEDB is planning on switching to NetMHC4.0 very soon. Once they do, NetMHC4.0 will automatically be used under the hood."

**Comment by jasonwalker80** [comment]
Also see #12
