### ISSUE TITLE
Different alignment of indels in DNA and RNA 

### ISSUE THREAD

**Issue by nilsrudqvist** [griffithlab/pVAC-Seq#293]
Hi,

This issue is not on your table, but I want to share it anyways since it is a peculiar and for me unexpected problem.

I work with a mouse dataset. We use BWA for alignment of DNA seq, and STAR for RNA seq. I have an insertion of A: CA>CAA. BWA seem to prefer having the insertion at position 2, and STAR at position 3. Both are equally right (!) - but in the pvacseq output file, the RNA VAF for variant will not match the location of the DNA according to the DNA seq (which we base our VCF on). 

Fortunately, I have very few indel variants that give rise to peptides with good binding. So I use IGV to look them up, and then use bam-readcount manually for the locations with this problem. For one certain variant in p53, I went from a RNA VAF of 0.2% to 99%, so I am happy I caught it...

I am not sure how to workaround this. I do not align the data myself, our core does that. What alignment software are you using for mouse data? Can you perhaps suggest a workaround for this problem?

Thanks,
Nils

**Comment by chrisamiller** [comment]
The accepted convention in this kind of data is to left align indels. As you're discovering, not all tools follow this convention correctly.  There are some suggestions in this thread for scripts that may help you normalize your data in this way. https://www.biostars.org/p/66843/

I'm going to go ahead and say this is out of scope for pvac-seq and close the issue.  Best of luck!

**Comment by susannasiebert** [comment]
Just to add to what @chrisamiller is saying, I think it might be worthwhile to also ask about this issue on the bam-readcount repository: https://github.com/genome/bam-readcount/. Dave Larson is usually pretty responsive. He might have some recommendations on how to best normalize your data.

**Comment by nilsrudqvist** [comment]
Hi, thanks for the quick response! Yes, didnt intend to ask for a fix :). Will look at the links. Thanks!
