### ISSUE TITLE
pVAC-Seq doesn't run on python 3.6

### ISSUE THREAD

**Issue by agraubert** [griffithlab/pVAC-Seq#296]
This is something @jneich found when I was helping him with the vaccine design PR.  It appears that some of the import semantics changed in 3.6 and `pvacseq` can't be run.  I'm going to go through the code and check for these instances, but it also may be worth enabling travis tests on other versions of python to catch this sort of issue

**Comment by susannasiebert** [comment]
I'm closing this issue mainly so that I can disable issues on this repository. We still should address this.
