### ISSUE TITLE
Mutated peptides generated from frameshift are unchanged compared to wildtype peptides

### ISSUE THREAD

**Issue by namsyvo** [griffithlab/pVAC-Seq#303]
Hi all,

In pvac-seq results, in many cases that MT Epitope Seq exist but not WT Epitope Seq (denoted by NA), the MT Epitope Seq are actually exist in the wildtype proteins at that position. I guess that is the problem of VEP because even for frameshift, the downstream proteins (produced by VEP) can be found in wild type proteins (also annotated by VEP) from the frameshift position.

Do you have any idea of that? For pvacseq, did you do some extra work to get peptides for neoantigen prediction? Or you just use peptides based on the downstream proteins produced by VEP? You can run whole pvacseq pipeline on the attached example to see the problem I described.
[chr7_91726541.vcf.txt](https://github.com/griffithlab/pVAC-Seq/files/1029841/chr7_91726541.vcf.txt)

**Comment by susannasiebert** [comment]
Hi Nam,
For frameshifts we decided to display the WT Epitope Seq as `NA` because the downstream mutated sequence is completely novel and has no relation to the wildtype sequence at the same position. As such, we found the comparison between the two to not be meaningful. In general, we will only include the corresponding WT epitope sequence when at least half of the amino acids between the mutant and the wildtype epitope match so you might also encounter this case with indels and MNPs.

**Comment by namsyvo** [comment]
Thank you for your help, Susanna. So it's clear for the first problem. How about the second problem, when the mutated peptides exist in the wildtype peptides in same gene locations? Have you run my example and check if that's VEP's problem? Thanks.

**Comment by susannasiebert** [comment]
When the mutant epitope sequence and the wildtype epitope sequence are the same we skip that sub-peptide position altogether and there would be no entry for it in the output report.

**Comment by namsyvo** [comment]
If you run my example, you would see that the sub-peptide still exist in the output record while it is the same with wildtype protein. That's why I said it might be the problem of VEP. Could you run my example to double check? Thanks.

**Comment by susannasiebert** [comment]
Please provide the pVAC-Seq output files and the annotated VEP VCF as well as the pvacseq command that you ran.

**Comment by namsyvo** [comment]
Please see in attached files the VEP VCF file (chr7_91726541.vcf.vep.txt), pVAC-Seq output files (chr7_91726541.final.tsv.txt). Command to run:
pvacseq run chr7_91726541.vcf.vep chr7_91726541 HLA-A*30:02,HLA-A*32:01,HLA-B*18:01,HLA-B*40:01,HLA-C*05:01,HLA-C*03:04 NetMHCpan chr7_91726541_pvacseq_results -e 9

[chr7_91726541.final.tsv.txt](https://github.com/griffithlab/pVAC-Seq/files/1053150/chr7_91726541.final.tsv.txt)
[chr7_91726541.vcf.vep.txt](https://github.com/griffithlab/pVAC-Seq/files/1053151/chr7_91726541.vcf.vep.txt)

**Comment by susannasiebert** [comment]
We don't compare a mutant epitope to the whole wildtype protein sequence to see whether it matches somewhere else in the protein. We only check whether the mutant and wildtype epitope at the same protein position are the same (with some caveats for indels).

**Comment by namsyvo** [comment]
I see. Thank you for your clarification.

**Comment by chrisamiller** [comment]
Your request would be covered by this outstanding issue, which is on the to-do list. 
https://github.com/griffithlab/pVAC-Seq/issues/222

I'm going to go ahead and close this up, but check back soon for updates that may include a fix for that issue.  Thanks!
