### ISSUE TITLE
Missing 'Gene Name' column

### ISSUE THREAD

**Issue by connorjliu** [griffithlab/pVAC-Seq#306]
Looking at my tsv output file I notice that the 'Gene Name' column is blank. The ensembl ID is listed so this is not the biggest issue, except that when I try to run the binding_filter command I receive the following error message: 

Traceback (most recent call last):
  File "/gscuser/yafeng/miniconda2/envs/python3/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/gscuser/yafeng/miniconda2/envs/python3/lib/python3.5/site-packages/pvacseq/pvacseq.py", line 84, in main
    args[0].func.main(args[1])
  File "/gscuser/yafeng/miniconda2/envs/python3/lib/python3.5/site-packages/pvacseq/lib/binding_filter.py", line 59, in main
    name = entry['Gene Name']
KeyError: 'Gene Name'

**Comment by susannasiebert** [comment]
Hi Connor,

This is an easy fix. We're working on a new release and I will make sure that it includes this bugfix. I would still be interested in figuring out why your tsv includes empty values for the Gene Name column. If you can point me to your annotated VCF and how you ran it through VEP, that would be very helpful. Feel free to IM me on our internal Slack for the info.

Thanks,
Susanna

**Comment by susannasiebert** [comment]
I chatted with Connor off-ticket and he was able to run the pipeline successfully. The VCF he used did not contain any gene annotation from VEP. With the change in #307 he was still able to get a successful run. Resolving.
