### ISSUE TITLE
Neoantigen prediction differences when running methods independently 

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVAC-Seq#308]
Hey guys,

I have seen some mutations could not predict neoantigens when running NetMHC, NetMHCpan, PickPocket, SMM and SMMPMBEC methods together. But when I run them independently they can able to predict the neoantigens which are IC50 < 500 nm. 

Example:
![image](https://user-images.githubusercontent.com/1926767/27573651-4163a08e-5b56-11e7-95a0-ce3d6aaad661.png)

Above neoantigens not seen when combing all the methods. I haven't changed any filters in both runs. 
Is there something I'm missing?

**Comment by susannasiebert** [comment]
By default, the binding filter gets applied to the median MT score. In your case, when running with multiple prediction algorithms, the scores from the other methods probably increase the median to above the 500nm default threshold. If you want to filter on the `Best MT Score` columns you will need to set the `-m, --top-score-metric` flag to `lowest`.
