### ISSUE TITLE
Inaccurate MT Epitope produced for frameshift mutation of type -/X

### ISSUE THREAD

**Issue by mnneveau** [griffithlab/pVAC-Seq#323]
The MT Epitope in the final.tsv produced by pVAC-Seq for a frameshift -/X mutation has the potential to be inaccurate due to the last amino acid of the WT Sequence being incorrectly overwritten. 

To reproduce:
`mkdir epitope_output_12 ; pvacseq run -b 500 -c 1 -e 8,9,10,11 /gscmnt/gc3018/info/medseq/tmp/mneveau/pvacSeq/H_XF-PICI012.annotated.vcf AML1 "HLA-A*02:01,HLA-A*03:01,HLA-B*57:01,HLA-B*07:02,HLA-C*06:02,HLA-C*07:02" --iedb-install-directory /gscmnt/gc2502/griffithlab/yafeng/ {NetMHC,NetMHCpan,PickPocket,SMM,SMMPMBEC} ./epitope_output_12`
(annotated vcf can also be found: /gscmnt/gc2785/tesla/batch2/xfer/variants/)

Expected:
In H_XF-PICI012.final.tsv:
For Transcript ENST00000280377 with Best_MT_Score_Method SMMPMBEC, the MT_Epitope_Seq would have an 'L' between "SYAE", from the WT seq, and "YQANV" from the MT seq. 
The DownstrSeq would insert between positions 345-346, not overwriting the last amino acid of the WT sequence, only for this type of frameshift mutation.

Actual:
In H_XF-PICI012.final.tsv:
For Transcript ENST00000280377 with Best_MT_Score_Method SMMPMBEC, the MT_Epitope_Seq produced is "SYAEYQANV" showing that the DownstrSeq "YQANVVWKV" was inserted one position too early.  
The DownstrSeq inserts between positions 344-345, overwriting the last amino acid of the WT sequence. 

![screenshot-mneveau linus86 -gscmnt-gc3018-cancer-genomics-medseq-tmp-mneveau-pvacseq-epitope_output_12-mhc_class_i](https://user-images.githubusercontent.com/26641617/28980532-bbcb5c60-7913-11e7-8f80-9a41df4530eb.png)

![screenshot-mneveau linus86 -gscmnt-gc3018-cancer-genomics-medseq-tmp-mneveau-pvacseq](https://user-images.githubusercontent.com/26641617/28980495-8ccda314-7913-11e7-9184-4f6c5fb24a14.png)

**Comment by susannasiebert** [comment]
I have verified that this is indeed a bug by manually applying the variant to the transcript cDNA sequence and translating it to the protein sequence. The resulting protein sequence does include the `L` amino acid.
