### ISSUE TITLE
vaccine design module in dev branch has problems

### ISSUE THREAD

**Issue by chrisamiller** [griffithlab/pVAC-Seq#326]
There are a few outstanding issues with the vaccine design module, (most of which date back to the original PR). It doesn't accept multiple input methods, uses different syntax than the 'run' command, etc. I'm working on cleaning things up and testing it.

**Comment by susannasiebert** [comment]
How is this issue coming along? I was planning on refactoring #324 but I wanted to make sure that we aren't overlapping our efforts.

**Comment by chrisamiller** [comment]
Need to carve out 2 or 3 hours to step through it. Hoping that's what I'll work on Friday
