### ISSUE TITLE
Coverage filter bug

### ISSUE THREAD

**Issue by connorjliu** [griffithlab/pVAC-Seq#327]
I applied the coverage_filter --normal-cov 0 --tdna-cov 0 --trna-cov 0 --normal-vaf 0 --tdna-vaf 0 --trna-vaf 0 --expn-val 1 on my sample.combined.parsed.tsv file to generate sample.1only.tsv which has a total of 75,000 predictions. However when I open the sample.combined.parsed.tsv file in microsoft excel and manually filter to select only for candidates with gene and transcript expression greater than 1, I get a list of 143,000 predictions. 

To double check, I found a predicted peptide that is present in the manually filtered list with gene and transcript expression values of 22 and 12, however this peptide is not present in the sample1.only.tsv file.

**Comment by susannasiebert** [comment]
@connorjliu and I chatted about this off-ticket and I asked him to put in a ticket. However, I just remembered that the normal-vaf threshold is different in that it will filter out everything above that value. All the other coverage and vaf threshold will filter out entries below that value. Does that explain the discrepancy you are seeing?

**Comment by connorjliu** [comment]
@susannasiebert yes that fixed the discrepancy, thank you for catching that!

**Comment by susannasiebert** [comment]
Awesome. Glad we figured it out.
