### ISSUE TITLE
does pvac supports predicting neoantigens from fusions?

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVAC-Seq#328]

**Comment by susannasiebert** [comment]
We're currently working on adding fusion support and should release this feature in the next couple of months.

**Comment by susannasiebert** [comment]
We're excited to announce pVACfuse, a tool for neoantigen prediction from fusions. pVACfuse, as well as pVACseq, is part of the new pVACtools immunotherapy suite of tools which can be installed by running `pip install pvactools`. You can find more information about pVACtools [here](http://pvactools.readthedocs.io/).
