### ISSUE TITLE
pVACseq won't convert CSV to TSV

### ISSUE THREAD

**Issue by runnerBio88** [griffithlab/pVAC-Seq#329]
Hi

I'm using pVACseq but it seems to get stuck somewhere (probably somwthing that I'm missing). 

The screen output:

> Allele HLA-B51:01 not validad. Skipping.
 Executing MHC Class I predictions
Converting VCF to TSV

I've executed this over the weekend and the tsv file appears to be empty, no error message besides the log file (which seems to be ok). The vcf file has around 400 lines

Is there any reason that after +2 days the program seems to be stuck in this step?
Also to add that pVACseq is using 1 core and 90G of RAM (as seen in htop).

Thanks for your time.

The issue was solved.

bamreadcount files were huge because no filtering was made.

Thanks and sorry for this silly question.

**Comment by runnerBio88** [comment]
I've been checking a little bit more, and it seems to be related to the files from bamreadcount. 
Those files weigth betwee 30 and 330G. Maybe I've not created them correctly.

**Comment by susannasiebert** [comment]
Glad you were able to resolve your issue. I will close this ticket.
