### ISSUE TITLE
Achieve GMT Feature Parity and support VCF

### ISSUE THREAD

**Issue by jasonwalker80** [griffithlab/pVAC-Seq#33]
GMT stands for [Genome Modeling Tools](http://gmt.genome.wustl.edu/) which is a framework that is a part of the larger GMS [Genome Model Sysetm](https://github.com/genome/gms).  pVAC-Seq was pulled out as a standalone application but some development continued on the GMT version.  This issue is to achieve parity with that code base.

The rough outline involves:
1. make VEP plugin available with activation instructions 
2. Define VCF based input and user protocol 
3. Updates to GenerateVariantSequences to support VCF 
4. Add NetMHC Indel support from GMTs 
5. point pVAC-Seq-tools at pVAC-Seq instead of GMTs 
6. (optional) point GMTs at pVAC-Seq

**Comment by hammer** [comment]
What's GMT?

**Comment by iskandr** [comment]
Not sure if this is helpful for you all, but we wrote [Varcode](https://github.com/hammerlab/varcode/issues) to predict the effect of an indel variant on all the annotated Ensembl transcripts it overlaps.

**Comment by jasonwalker80** [comment]
@hammer I updated the description of this issue to be a bit more verbose.

**Comment by serge2016** [comment]
Hello to all!
@jasonwalker80 Could you tell me, please, when are you going to implement at least first two steps?

**Comment by susannasiebert** [comment]
@serge2016 Our current deadline for this milestone is June 21st.

**Comment by chrisamiller** [comment]
@hammer - GMT is our internal pipeline (http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004274), which currently runs a somewhat more sophisticated version of this code with many internal dependencies

**Comment by jasonwalker80** [comment]
All of the requirements for this Epic have been met.  Closing.
