### ISSUE TITLE
Missense MT amino acid does not match the one predicted by VEP

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVAC-Seq#333]
This is an example of a problematic transcript
```
A|missense_variant&splice_region_variant|MODERATE|MYO15A|ENSG00000091536|Transcript|ENST00000418233|protein_coding|9/24||||1380|758|253|G/E|gGg/gAg|||1||HGNC|HGNC:7594|||MKALFAQNQLDTQKPLVTESVKRAVVSTARDTWEVYFSRIFPATGSVGTGVQLLAVSHVGIKLLRMVKGGQEAGGQLRVLRAYSFADILFVTMPSQNMLEFNLASEKVILFSARAHQVKTLVDDFILELKKDSDYVVAVRNFLPEDPALLAFHKGDIIHLQPLEPPRVGYSAGCVVRRKVVYLEELRRRGPDFGWRFGTIHGRVGRFPSELVQPAAAPDFLQLPTEPGRGRAAAVAAAVASAAAAQEVGRRREGPPVRARSADHGEDALALPPYTMLEFAQKYFRDPQRRPQDGLRLKSKEPRESRTLEDMLCFTKTPLQESLIELSDSSLSKMATDMFLAVMRFMGDAPLKGQSDLDVLCNLLKLCGDHEVMRDECYCQVVKQITDNTSSKQDSCQRGWRLLYIVTAYHSCSEVLHPHLTRFLQDVSRTPGLPFQGIAKACEQNLQKTLRFGGRLELPSSIELRAMLAGRSSKRQLFLLPGGLERHLKIKTCTVALDVVEEICAEMALTRPEAFNEYVIFVVTNRGQHVCPLSRRAYILDVASEMEQVDGGYMLWFRRVLWDQPLKFENELYVTMHYNQVLPDYLKGLFSSVPASRPSEQLLQQVSKLASLQHRAKDHFYLPSVREVQEYIPAQLYRTTAGSTWLNLVSQHRQQTQALSPHQARAQFLGLLSALPMFGSSFFFIQSCSNIAVPAPCILAINHNGLNFLSTETHELMVKFPLKEIQSTRTQRPTANSSYPYVEIALGDVAAQRTLQLQLEQVRAGEVLDGRGLSLSPAGTGTVSCGGRARGEPAQCP
```

This is a `G/E` amino acid change but the amino acid at position `253` of the transcript is an `E`, not a `G`. However, the amino acid at position `254` is a `G`. This makes me wonder whether for this particular transcript the position is 0-based, instead of 1-based. I'm not sure why that would be or how to tell if that is the case.

Right now, we do not filter out these cases, which results in incorrect mutant peptide sequence getting created.

**Comment by susannasiebert** [comment]
The variant in question is `17	18157899	row995	G	A` and the VCF can be found at /gscuser/ssiebert/tmp/Patient01.snvs.indels.filtered.overlaps.sanger.VEPout.vcf.

**Comment by susannasiebert** [comment]
I made local branch that would skip these cases which resulted in 78 peptide sequences getting created for the fasta, vs 192 without skipping these cases, as well as 60% less epitopes getting predicted.

**Comment by susannasiebert** [comment]
@malachig and @chrisamiller found that the VCF was created using build 37 but annotated with VEP build 38. This is causing the inconsistency we are seeing. We will change pVAC-Seq to die if we encounter cases of mismatched wildtype amino acids. Chris provided me with a few VCFs to use for testing to ensure that this won't cause additional problems.

**Comment by susannasiebert** [comment]
I ran the example VCFs that @chrisamiller provided and haven't found any mismatches in those. I made a PR (#334) to die if a mismatch occur and print a helpful error message that suggests that the user might've used the wrong reference build when annotating VEP.

**Comment by malachig** [comment]
Wonderful @susannasiebert.  Very reassuring to know that this was an issue with the input VCF and not indicative of any major bug!  Nevertheless I think adding this check will save us effort and give us peace of mind going forward.  It is just so easy for these kind of build compatibility issues to occur.
