### ISSUE TITLE
The TSV file is empty. Please check that the input VCF contains missense, inframe indel, or frameshift mutations.

### ISSUE THREAD

**Issue by zhangb1** [griffithlab/pVAC-Seq#335]
Hi,

I tried to use the pVAC-Seq, using vep vcf ,but I get the error:

```
pvacseq run TEST.vep.vcf TUMOR HLA-C*01:09 NetMHC PickPocket NNalign . -e 9,10 --tdna-vaf 20 --net-chop-method cterm --netmhc-stab --top-score-metric=lowest -d full --keep-tmp-files
```
**The TSV file is empty. Please check that the input VCF contains missense, inframe indel, or frameshift mutations.**

When I took a look at the vep.vcf ,I can see the missense mutations and frameshift there

`
1       248616276       .       A       G       .       PASS    CSQ=G|ENSG00000196240|ENST00000342927|Transcript|missense_variant|200|178|60|M/V|Atg/Gtg||MODERATE||1||OR2T2|HGNC|14725|||MGMEGLLQNSTNFVLTGLITHPAFPGLLFAIVFSIFVVAITANLVMILLIHMDSRLHTPMYFLLSQLSIMDTIYICITVPKMLQDLLSKDKTISFLGCAVQIFLYLTLIGGEFFLLGLMAYDRYVAVCNPLRYPLLMNRRVCLFMVVGSWVGGSLDGFMLTPVTMSFPFCRSREINHFFCEIPAVLKLSCTDTSLYETLMYACCVLMLLIPLSVISVSYTHILLTVHRMNSAEGRRKAFATCSSHIMVVSVFYGAAFYTNVLPHSYHTPEKDKVVSAFYTILTPMLNPLIYSLRNKDVAAALRKVLGRCGSSQSIRVATVIRKG  DP:FDP:SDP:SUBDP:AU:CU:GU:TU    96:0:0:0:79,95:0,0:17,21:0,0
`
Can someone help this ?Thank you .

**Comment by susannasiebert** [comment]
Your VCF is missing the GT (genotype) field. pVAC-Seq only includes variants that were called and are heterozygous or homogenous variant.

**Comment by zhangb1** [comment]
Thank you !!
