### ISSUE TITLE
The TSV file is empty. Please check that the input VCF contains missense, inframe indel, or frameshift mutations.

### ISSUE THREAD

**Issue by DanUNC** [griffithlab/pVAC-Seq#336]
Hello, 

I am testing a vcf file I had generated using mutect2 and annotated in VEP according to instructions.

Executing MHC Class I predictions
Converting VCF to TSV
Completed
The TSV file is empty. Please check that the input VCF contains missense, inframe indel, or frameshift mutations.

Counting missence mutations there are 700 in my file.

Here is the pertinent VCF header:

##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence   annotations from Ensembl VEP. Format:   Allele\|Consequence\|IMPACT\|SYMBOL\|Gene\|Feature_type\|Feature\|BIOTYPE\|EXON\|INTRON\|HGVSc\|HGVSp\|cDNA_position\|CDS_position\|Protein_position\|Amino_acids\|Codons\|Existing_variation\|DISTANCE\|STRAND\|FLAGS\|SYMBOL_SOURCE\|HGNC_ID\|DownstreamProtein\|ProteinLengthChange\|WildtypeProtein">
--

Here is an example of a missense in the body of my vcf:

chr10 | 5022242 | . | C | A | . | alt_allele_in_normal;t_lod_fstar | ECNT=1;HCNT=1;MAX_ED=.;MIN_ED=.;NLOD=20.25;TLOD=4.05;CSQ=A\|missense_variant\|MODERATE\|\|CCDS56679.1\|Transcript\|CCDS56679.1\|protein_coding\|17/17\|\|\|\|2615\|2615\|872\|R/I\|aGa/aTa\|\|\|-1\|\|\|\|\|\|MVVAEDLHGPRMAEDSSVDADLPDCDCDVSRVKKLKETLVAVQQLDKNMGSLRTWLAHMESELAKPIVYDSCNSEEIQRKLNEQQELQRDIEKHSTGVASVLNLCEVLLHDCDACATDAECDSIQQATRNLDRRWRNICAMSMERRLKIEETWRLWQKFLDDYSRFEDWLEVSERTAAFPSSSGVLYTVAKEELKKFEAFQRQVHESLTQLELINKQYRRLARENRTDSACSLRQMVHGGNQRWDDLQKRVTSILRRLKHFISQREEFETARDSILVWLTEMDLQLTNIEHFSECDVQAKIKQLKAFQQEISLNHNKIEQIIAQGEQLIEKSEPLDAAVIEEELDELRRYCQEVFGRVERYHKKLIRLPLPDDHDLSDRELDLEDSTALSDLRWQDPSADGMPSPQPSSNPSLSLPQPLRSERSGRDTPASVDSIPLEWDHDYDLSRDLESASRTLPSEDEEGEEDKEFYLRGAVGLSGDPSSLESQMRQLDKALDDSRFQIQQTANILRSKTPTGPDLDTSYKGYMKLLGECSGSIDSVRRLEHKLAEEESFPGFVNLNSTETQTAGVIDRWELLQAQAMSKELRMKQNLQKWQQFNSDLNNIWAWLGETEEELDRLQHLALSTDIHTIESHIKKLKELQKAVDHRKAIILSINLCSSEFTQADSKESHDLQDRLSQMNGRWDRVCSLLEDWRGLLQDALMQCQEFHEMSHALLLMLENIDRRKNEIVPIDSTLDPETLQDHHKQLMQIKQELLKSQLRVASLQDMSRQLLVNAEGSDCLEAKEKVHVIGNRLKLLLKEVSHHIKDLEKLLDMSSSQQDLSSWSSADELDTSGSVSPTSGRSTPNRQKSPRGKCSLSQPGPSVSSPKSRSTRDGSDSSRSDPRPERVGRAFLFRILRAALPFQLLLLLLIGLTCLVPMSEKDYSCALSNNFARSFHPMLRYTNGPPPL | GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1 | 0/0:94,2:0.021:2:0:0.00:3354,73:45:49
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

Any assistance is greatly appreciated

**Comment by susannasiebert** [comment]
This particular variant has a genotype of `0/0` so it's homozygous reference. pVAC-Seq only includes variants that were called heterozygous or homozygous variant.

**Comment by iichelhadi** [comment]
I have a similar issue using strelka2 generated vcf. I used `vcf-genotype-annotator` to add `0/1` genotype info since strelka does not provide that info. Example first line of VEP.vcf
```
chr1    17407   .       G       A       .       LowEVS  SOMATIC;QSS=36;TQSS=1;NT=ref;QSS_NT=36;TQSS_NT=1;SGT=GG->AG;DP=663;MQ=28.8;MQ0=337;ReadPosRankSum=-0.99;SNVSB=0.0;SomaticEVS=1.05;CSQ=A|downstream_gene_var
iant|MODIFIER|DDX11L1|ENSG00000223972|Transcript|ENST00000450305|transcribed_unprocessed_pseudogene||||||||||rs372841554|1|3737|1||SNV|HGNC|HGNC:37102|||||||||||||||||||||||||||0.02501|0.00875|0.01802|0.007812|0
.0281|0.02822|0.02515|0.02129|0.05443|0.05443|gnomAD_SAS|||||||||||,A|downstream_gene_variant|MODIFIER|DDX11L1|ENSG00000223972|Transcript|ENST00000456328|processed_transcript||||||||||rs372841554|1|2998|1||SNV|H
GNC|HGNC:37102|YES|||1|||||||||||||||||||||||0.02501|0.00875|0.01802|0.007812|0.0281|0.02822|0.02515|0.02129|0.05443|0.05443|gnomAD_SAS|||||||||||,A|intron_variant&non_coding_transcript_variant|MODIFIER|WASH7P|E
NSG00000227232|Transcript|ENST00000488147|unprocessed_pseudogene||5/10|ENST00000488147.1:n.575-39C>T|||||||rs372841554|1||-1||SNV|HGNC|HGNC:38034|YES||||||||||||||||||||||||||0.02501|0.00875|0.01802|0.007812|0.0281|0.02822|0.02515|0.02129|0.05443|0.05443|gnomAD_SAS|||||||||||,A|non_coding_transcript_exon_variant|MODIFIER|MIR6859-1|ENSG00000278267|Transcript|ENST00000619216|miRNA|1/1||ENST00000619216.1:n.30C>T||30/68|||||rs372841554|1||-1||SNV|HGNC|HGNC:50039|YES||||||||||||||||miRNA_stem||||||||||0.02501|0.00875|0.01802|0.007812|0.0281|0.02822|0.02515|0.02129|0.05443|0.05443|gnomAD_SAS||||||||||| GT:DP:FDP:SDP:SUBDP:AU:CU:GU:TU .:160:0:0:0:2,6:0,0:158,368:0,0 .:113:0:0:0:6,13:0,1:107,275:0,0        0/1:.:.:.:.:.:.:.:.
```
Is there a way to deal with this issue?
kind regards

EL

**Comment by susannasiebert** [comment]
Yes, that is the recommended way. It looks like you are adding a dummy sample, though. We recently added the ability to use the vcf-genotype-annotator to add a GT field for samples where this field doesn't already exist.

From https://vatools.readthedocs.io/en/latest/vcf_genotype_annotator.html
> It can also be used to add a GT field to an existing sample, e.g. for VCFs created by Strelka which does not output a GT field for its calls.

You just need to pick the existing tumor sample as your `sample_name` argument.

**Comment by iichelhadi** [comment]
> Yes, that is the recommended way. It looks like you are adding a dummy sample, though. We recently added the ability to use the vcf-genotype-annotator to add a GT field for samples where this field doesn't already exist.
> 
> From https://vatools.readthedocs.io/en/latest/vcf_genotype_annotator.html
> 
> > It can also be used to add a GT field to an existing sample, e.g. for VCFs created by Strelka which does not output a GT field for its calls.
> 
> You just need to pick the existing tumor sample as your `sample_name` argument.

Thank you. I understand the mistake I made.

**Comment by iichelhadi** [comment]
> To add to Susanna's comment: the reasons that Strelka does not output a GT field are complicated - see this issue: [Illumina/strelka#16](https://github.com/Illumina/strelka/issues/16)
> 
> In one of our somatic pipelines, we use this tool to update the GT field to be useful information - you're welcome to use that or code up something similar: https://github.com/genome/analysis-workflows/blob/master/definitions/tools/add_strelka_gt.cwl

Thank you. Unfortunately, I am not sure how to use your code as I am not that well versed in bioinformatics.
