### ISSUE TITLE
PredTAP/SVMTAP

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVAC-Seq#337]
Hi guys,

Any plans of implementing TAP binding affinity in pVAC-Seq. This could add one more step in the filtration of neoantigens.

**Comment by malachig** [comment]
We have certainly thought of it. Care to share your thoughts on any specific TAP predictors?

**Comment by susannasiebert** [comment]
@venkataddala I made an issue for this request in the [pVACtools repository](https://github.com/griffithlab/pVACtools). The new issue can be found [here](https://github.com/griffithlab/pVACtools/issues/66).
