### ISSUE TITLE
Tumor Depth/expression + python versions

### ISSUE THREAD

**Issue by ktroule** [griffithlab/pVAC-Seq#339]
Hello
I'm trying pVAC-seq with some of the original data you used in your papaer (Mel218).

I've been able to follow the whole pipeline, but at the final report I lack information of the tumor DNA depth and tumor expression. Not sure why is this so, as in the original vcf file I have the DP variable (I filter out those with less than 15dp). I've also input the fpkm gene matrix from RNA, and as I've checked some of the fpkm values are slightly higher than 0. Not sure what I might be doing wrong.

On the other hand. pVAC-seq requieres python 3.5, but one of its dependencies (predict_binding.py) requiere python 2.7 (it gives problems with the print functions that change over these versions). Any solution for this? I cannot use this function in local.

And last. Would it be possible to have the original output of pVACseq for the patient MEL218 to compare against my tries.

Thanks for you time.

**Comment by susannasiebert** [comment]
Hi Kevin,

The current implementation of pVAC-Seq requires you to run bam-readcount and cufflinks separately and input these tools' output files into your commend using the `--additional-input-file-list` option. We currently do not support VCF annotations for depth/VAF/expression but are working on adding that functionality. Please see http://pvac-seq.readthedocs.io/en/latest/prerequisites.html#optional-preprocessing for more information.

Regarding the python version, are you using conda as recommended in the documentation?

Thanks,
Susanna

**Comment by susannasiebert** [comment]
@ktroule We are transitioning the pVACseq issue tracking to the [pVACtools repository](https://github.com/griffithlab/pVACtools). If you would still like assistance with this error, please make a new issue there.
