### ISSUE TITLE
Support for VCF as input

### ISSUE THREAD

**Issue by serge2016** [griffithlab/pVAC-Seq#34]
Hello. Could you add the support of VCF v4.1 file format as input? I can't find any working util to convert my VCF file to the format, requested for pVAC-Seq as input. Or can you recommend any?

This is a part of #33

**Comment by jasonwalker80** [comment]
@serge2016 a conversion command was added on our python branch by pull request #51.
The new converter command will be a part of our next pVAC-Seq release available later this week.

**Comment by jasonwalker80** [comment]
The 2.0.0 version of pVAC-Seq is now available.  Please see the README for install instructions via PyPI and pip.  Closing.
