### ISSUE TITLE
File containing results of somatic variant calling

### ISSUE THREAD

**Issue by Veliborka** [griffithlab/pVAC-Seq#340]
Is it possible to provide us with the vcf file that you got after performing somatic variant calling?

**Comment by susannasiebert** [comment]
Hi,
I apologize but I don't think I quite understand your request. Are you looking for the unannotated version of the example input vcf before VEP annotation?
Thanks,
Susanna

**Comment by Veliborka** [comment]
Hello Susanna,

Yes, that is what I am looking for.

09.01.2018. 6:54 PM, "Susanna Kiwala" <notifications@github.com> je
napisao/la:

**Comment by susannasiebert** [comment]
The unannotated input file is attached to this comment. 

Please be aware that the `pvacseq` package has been superseded by `pvactools` and will not be maintained or updated further. You can install pVACtools by running `pip install pvactools`. Your `pvacseq` commands will stay the same. pVACtools also contains our new tools pVACfuse for predicting neoepitopes from fusions and pVACvector for DNA-vector vaccine design. Please see [the documentation](http://pvactools.readthedocs.io/) for more information.

[pvacseq_unannotated_input.vcf.zip](https://github.com/griffithlab/pVAC-Seq/files/1623055/pvacseq_unannotated_input.vcf.zip)
