### ISSUE TITLE
Duplicate TSV indexes

### ISSUE THREAD

**Issue by erikla** [griffithlab/pVAC-Seq#341]
After Splitting TSV into smaller chunks, processing continues until it parses IEDB output and immediately after that I receive the following message: Duplicate TSV indexes.  Any recommendations?

**Comment by susannasiebert** [comment]
It's difficult to know why that my be without having the full output directory. Was this by any chance  a run that was restarted in the same output directory? If so, I would try to run it with an empty output directory.

Please be aware that the `pvacseq` package has been superseded by `pvactools` and will not be maintained or updated further. You can install pVACtools by running `pip install pvactools`. Your `pvacseq` commands will stay the same. pVACtools also contains our new tools pVACfuse for predicting neoepitopes from fusions and pVACvector for DNA-vector vaccine design. Please see [the documentation](http://pvactools.readthedocs.io/) for more information.

**Comment by erikla** [comment]
No, this was a fresh run with no prior directory.  I am using the pvavseq command with pvactools.
One smaller output looks like:
Converting .vcf to TSV
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-100
Splitting TSV into smaller chunks - Entries 101-200
Splitting TSV into smaller chunks - Entries 201-300
Splitting TSV into smaller chunks - Entries 301-362
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Entries 1-200
Generating Variant Peptide FASTA and Key Files - Entries 201-400
Generating Variant Peptide FASTA and Key Files - Entries 401-600
Generating Variant Peptide FASTA and Key Files - Entries 601-724
Completed
Processing entries for Allele HLA-A*01:01 and Epitope Length 8 - Entries 1-200
Running IEDB on Allele HLA-A*01:01 and Epitope Length 8 with Method NetMHC - Entries 1-200
Completed
Running IEDB on Allele HLA-A*01:01 and Epitope Length 8 with Method PickPocket - Entries 1-200
Completed
Parsing IEDB Output for Allele HLA-A*01:01 and Epitope Length 8 - Entries 1-200
Duplicate TSV indexes

Do you think this could be an issue due to splitting the vcf file?  Maybe I'll try to write a vcf by chromosome, annotate with VEP and then try pvacseq again.

**Comment by susannasiebert** [comment]
I'm not sure. Would it be possible for you to share the vcf you are running as well as the exact command you are using?

**Comment by susannasiebert** [comment]
You can split your VEP-annotated vcf into smaller chunks manually (no need to annotate VCFs separately). Just make sure to maintain the header between each file. If you are using a local IEDB install you can also increase the `--fasta-size` parameter so that your intermediate variants TSV does not get chunked into smaller files. I'm not 100% sure if that will solve this problem. If you would be able to provide the full VCF I could investigate the underlying cause.
