### ISSUE TITLE
pVAC-Seq peptide length control problem

### ISSUE THREAD

**Issue by sashakotov2** [griffithlab/pVAC-Seq#342]
My problem is that several pvacseq runs were with this error:
![pvacseq_error](https://user-images.githubusercontent.com/24713989/35032771-34656bc4-fb79-11e7-99b6-8593d3a29d8c.png)

I ran netMHCIIpan with the fasta.file on the netMHCIIpan server (http://www.cbs.dtu.dk/services/NetMHCIIpan/). It turned out that fasta.file has peptide with length = 14, and this is the reason for my pvacseq error. 

Fasta file:
[OUTPUT_31.fa.split_6401-6600.tar.gz](https://github.com/griffithlab/pVAC-Seq/files/1638203/OUTPUT_31.fa.split_6401-6600.tar.gz)

Are there any ways to manage it? 

Thanks in advance

**Comment by susannasiebert** [comment]
Please be advised that pVAC-Seq is now part of the pVACtools package and we are transitioning our issue tracking to the [pVACtools GitHub repository](https://github.com/griffithlab/pVACtools). I already made a copy of this issue in our new repository and will reply there. The new issue can be found [here](https://github.com/griffithlab/pVACtools/issues/65)
