### ISSUE TITLE
mismatch between the actual wildtype amino acid and the expected amino acid

### ISSUE THREAD

**Issue by huangxiaogua** [griffithlab/pVAC-Seq#343]
hello,when I run pvacseq the results indicated an ERROR: There was a mismatch between the actual wildtype amino acid and the expected amino acid. Did you use the same reference build version for VEP that you used for creating the VCF? Following are the details:

Generating Variant Peptide FASTA and Key Files - Entries 801-1000
Generating Variant Peptide FASTA and Key Files - Entries 1001-1200
ERROR: There was a mismatch between the actual wildtype amino acid and the expected amino acid. Did you use the same reference build version for VEP that you used for creating the VCF?
{'reference': 'A', 'stop': '145365433', 'start': '145365432', 'index': 'NBPF10.NM_001039703.5.missense.3426H/R', 'transcript_expression': 'NA', 'trna_depth': 'NA', 'tdna_vaf': 'NA', 'tdna_depth': 'NA', 'normal_depth': 'NA', 'transcript_name': 'NM_001039703.5', 'gene_expression': 'NA', 'wildtype_amino_acid_sequence': 'MVVSAGPWSSEKAEMNILEINETLRPQLAEKKQQFRSLKEKCFLTQLAGFLANRQKKYKYEECKDLIKFMLRNERQFKEEKLAEQLKQAEELRQYKVLVHSQERELTQLREKLREGRDASRSLYEHLQALLTPDEPDKSQGQDLQEQLAEGCRLAQHLVQK

I had got vcf file from sentieon TNseq by online app, the Reference genome was ucsc_hg19.fa.gz and GATK resource bundle was hg19.gatk.resource.bundle.tar.gz. 
The vep command was  `./vep --cache --port 3337 -i /home/jm/DATA/output_p0001.vcf  --format vcf -o /home/jm/DATA/p0001vepout3.vcf --vcf --offline --use_given_ref --no_stats --symbol --terms SO --dir_plugins /home/jm/vep/dir/Plugins --plugin Downstream --plugin Wildtype. ` 
 I used the vep_GRCh37 references.

Then I run the pvacseq with the command `pvacseq run p0001vepout3.vcf Test HLA-A*11:01 NetMHC resultc05  -e 9 --tdna-vaf 20 --net-chop-method cterm --netmhc-stab --top-score-metric=lowest -d full --keep-tmp-files`
Whether my references has some errors? Thank you

**Comment by susannasiebert** [comment]
The pVAC-Seq repository is obsolete and has been replaced by https://github.com/griffithlab/pVACtools. I ported your issue to the new repository. It can be found here (https://github.com/griffithlab/pVACtools/issues/101). Closing this issue.
