### ISSUE TITLE
Errors: VCF file contains more than one sample & unrecognized arguments

### ISSUE THREAD

**Issue by osmium96** [griffithlab/pVAC-Seq#345]
I am running pvacseq on an annotated .vep.vcf file and am receiving the error message **ERROR: VCF file contains more than one sample**, however my colleague was able to run the exact same command (see below) on the exact same file successfully. 

`pvacseq run TCGA-EE-A29V.vep.vcf TUMOR HLA-A*03:01,HLA-A*03:01,HLA-B*07:02,HLA-B*14:02,HLA-C*07:02,HLA-C*08:02 NetMHCpan . -e 8,9,10,11 --iedb-install-directory directory_name`

Furthermore, I am receiving a separate error if I attempt to add a flag by writing "-t 1" in the command (see below) for number of threads. This error reads **pvacseq run: error: unrecognized arguments: {1}**

`pvacseq run TCGA-EE-A29V.vep.vcf TUMOR HLA-A*03:01,HLA-A*03:01,HLA-B*07:02,HLA-B*14:02,HLA-C*07:02,HLA-C*08:02 NetMHCpan . -e 8,9,10,11 --iedb-install-directory directory_name -t 1`

Some additional context:
- The file in question has two samples (NORMAL and TUMOR) and we specified the sample_name as suggested. Given that my colleague experienced success on his machine, we do not think this is a problem related to the file. 
- I am running pvacseq in an Anaconda environment for Python 3.5.6 on a Linux cluster. I am using pvacseq version 4.0.10. 

Please advise on how we might resolve this issue!

**Comment by susannasiebert** [comment]
You don't have the correct package installed. The `pvacseq` package is outdated and has been superseded by the `pvactools` package. Please uninstall the pvacseq package (`pip uninstall pvacseq`) and install `pvactools` instead (`pip install pvactools`). The latest version of the `pvactools` package is `1.5.7`. The command line arguments look correct to me. Please rerun it after you install the correct package. If you still encounter errors please attach your `TCGA-EE-A29V.vep.vcf ` for further debugging.
