### ISSUE TITLE
FROM FASTQ FILES

### ISSUE THREAD

**Issue by neoscreen** [griffithlab/pVAC-Seq#346]
Hi
Are you planning in a future version to start pvacseq from FastQ files ?
Thank you

**Comment by susannasiebert** [comment]
There are no plans on adding fastq support to pVACseq. Instead, the McDonnell Genome Institute offers an open source CWL workflow that includes somatic variant detection and RNAseq analysis and runs pVACseq. You can find this workflow here: https://github.com/genome/analysis-workflows/blob/master/definitions/pipelines/immuno.cwl. We are currently working on adding fusion calling and pVACfuse to this pipeline as well.

Please be aware, that the pVACseq tool has moved and is now part of pVACtools, which can be found at https://github.com/griffithlab/pVACtools. Please create any additional issues you might have in the pVACtools repo instead. I will be closing this issue and turning off issues for this repo.
