### ISSUE TITLE
Add NetMHC Indel support

### ISSUE THREAD

**Issue by jasonwalker80** [griffithlab/pVAC-Seq#44]

**Comment by susannasiebert** [comment]
https://github.com/griffithlab/pVAC-Seq/pull/52 adds indel support to generate_fasta,py. We still need to update the netMHC parser.

**Comment by susannasiebert** [comment]
#58 updates parse_output.py to handle indels

**Comment by susannasiebert** [comment]
#60 updates binding_filter.py to handle indels.
