### ISSUE TITLE
Add test data files to demonstrate usage of the pipeline

### ISSUE THREAD

**Issue by malachig** [griffithlab/pVAC-Seq#7]
- Input file of annotated variants
- Example file from pVAC-Seq that has been appended with coverage information. Reference and variant read count for normal DNA, tumor DNA, and tumor RNA. And gene expression values for tumor RNA.

**Comment by jasonwalker80** [comment]
#38 separates test_data from example_data.  This issue pertains to example_data.  @jhundal does the example_data fully cover the examples listed in this issue?

**Comment by jasonwalker80** [comment]
I'm going to resolve this as we have the example_data along with instructions for running pVAC-Seq.  The example data does not include all of the use-cases you mentioned; however, Epic #75 covers the addition and/or documentation of adding read counts, expression values etc.  As we add that functionality or document the process for adding that info, we should include it in the example_data as a integration test.  Closing for now unless objection.
