### ISSUE TITLE
Add NetChop as optional step in workflow

### ISSUE THREAD

**Issue by jasonwalker80** [griffithlab/pVAC-Seq#74]
GenerateFastaForNetChop.pl is still left in the bin from the perl version.  Also pVAC-Seq-tools has this same functionality for running NetChop for peptide cleavage info.

**Comment by chrisamiller** [comment]
Just as an FYI, the tools version actually hits a local clone of this tool: https://github.com/chrisamiller/netChopScraper

I have (sort of accidentally) used that on as many as 50k peptides, 100 at a time, so they don't appear to be doing any strict rate limiting.  At some point we may also want to investigate alternative peptide cleavage prediction algorithms.
