### ISSUE TITLE
Interactive report generation including visualizations.

### ISSUE THREAD

**Issue by jasonwalker80** [griffithlab/pVAC-Seq#77]
```
start with TSV output from pVAC-Seq
sort on values ex. binding affinity
prioritize - low binding affinity, high expression, high VAF
```

**Comment by susannasiebert** [comment]
Since we are getting pretty close to releasing this feature I will close this issue without making a corresponding one on the pVACtools repo. We should make more specific issues for the remaining tasks if they don't exist yet.
