### ISSUE TITLE
Installation of pVAC-Seq

### ISSUE THREAD

**Issue by serge2016** [griffithlab/pVAC-Seq#79]
Hello! It's not obvious to install pVAC-Seq using pip ...
For Ubuntu 14.04:
sudo apt-get --yes --force-yes install \
    software-properties-common \
sudo apt-add-repository -y ppa:fkrull/deadsnakes
sudo apt-get update
sudo apt-get --yes --force-yes install python3.5 **python3-pip**
sudo **pip3** install pvacseq

Update the installation instructions, please...

**Comment by susannasiebert** [comment]
pVAC-Seq requires python 3.5 which currently isn't clear from the instructions. We will make sure to update the installation instructions accordingly. However, once python 3.5 is installed you should be able to run `pip install pvacseq` to install. Using `pip3` shouldn't be necessary. Did you get an error when trying to install pVAC-Seq using `pip`?

**Comment by serge2016** [comment]
@susannasiebert Yes, I did. I had to run exactly pip3.
Moreover, I had to:
sudo rm /usr/bin/python3
sudo ln -s /usr/bin/python3.5 /usr/bin/python3

**Comment by susannasiebert** [comment]
What error message did you receive when trying to install using `pip`?

**Comment by serge2016** [comment]
And now I have this error:
$ pvacseq
Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 7, in <module>
    from pvacseq.pvacseq import main
ImportError: No module named 'pvacseq'

**Comment by serge2016** [comment]
root@78e8e071146d:/# pip install pvaqseq
Downloading/unpacking pvaqseq
  Could not find any downloads that satisfy the requirement pvaqseq
Cleaning up...
No distributions at all found for pvaqseq
Storing debug log for failure in /root/.pip/pip.log

**Comment by susannasiebert** [comment]
You had a typo in your command. It's `pvacseq`, not `pvaqseq`.

**Comment by serge2016** [comment]
root@78e8e071146d:/# pip install pvacseq
Downloading/unpacking pvacseq
  Could not find any downloads that satisfy the requirement pvacseq
Cleaning up...
No distributions at all found for pvacseq
Storing debug log for failure in /root/.pip/pip.log
root@78e8e071146d:/# which pip
/usr/bin/pip
root@78e8e071146d:/# ls -la /usr/bin/pip*
-rwxr-xr-x 1 root root 281 Jun 16  2015 /usr/bin/pip
-rwxr-xr-x 1 root root 283 Jun 16  2015 /usr/bin/pip2
-rwxr-xr-x 1 root root 284 Jun 16  2015 /usr/bin/pip3
root@78e8e071146d:/#

**Comment by agraubert** [comment]
So, if I'm understanding you, `pip3 install pvacseq` looked like it installed, but the console entry point isn't working?
If so, could you post the output of `pip3 list`?

**Comment by serge2016** [comment]
root@78e8e071146d:/# pip3 install pvacseq
Downloading/unpacking pvacseq
  Downloading pvacseq-2.0.0-py3-none-any.whl (307kB): 307kB downloaded
Downloading/unpacking PyVCF (from pvacseq)
  Downloading PyVCF-0.6.8.tar.gz
  Running setup.py (path:/tmp/pip_build_root/PyVCF/setup.py) egg_info for package PyVCF

Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python3/dist-packages (from PyVCF->pvacseq)
Installing collected packages: pvacseq, PyVCF
  Running setup.py install for PyVCF

    Fixing build/lib/vcf/parser.py build/lib/vcf/utils.py build/lib/vcf/model.py build/lib/vcf/sample_filter.py build/lib/vcf/__init__.py build/lib/vcf/filters.py build/lib/vcf/test/test_vcf.py build/lib/vcf/test/__init__.py build/lib/vcf/test/prof.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    Fixing build/lib/vcf/parser.py build/lib/vcf/utils.py build/lib/vcf/model.py build/lib/vcf/sample_filter.py build/lib/vcf/__init__.py build/lib/vcf/filters.py build/lib/vcf/test/test_vcf.py build/lib/vcf/test/__init__.py build/lib/vcf/test/prof.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    changing mode of build/scripts-3.5/vcf_melt from 644 to 755
    changing mode of build/scripts-3.5/vcf_filter.py from 644 to 755
    changing mode of build/scripts-3.5/vcf_sample_filter.py from 644 to 755
    changing mode of /usr/local/bin/vcf_sample_filter.py to 755
    changing mode of /usr/local/bin/vcf_filter.py to 755
    changing mode of /usr/local/bin/vcf_melt to 755
Successfully installed pvacseq PyVCF
Cleaning up...

root@78e8e071146d:/# pip3 list
chardet (2.2.1)
colorama (0.2.5)
html5lib (0.999)
pip (1.5.4)
pvacseq (2.0.0)
pycurl (7.19.3)
pygobject (3.12.0)
python-apt (0.9.3.5ubuntu2)
PyVCF (0.6.8)
requests (2.2.1)
setuptools (3.3)
six (1.5.2)
unattended-upgrades (0.1)
urllib3 (1.7.1)
wheel (0.24.0)

**Comment by agraubert** [comment]
I'd first `pip3 uninstall pvacseq` just to clear up whatever it's left behind, then I'd try updating pip from 1.5.4, to it's most recent version 8.1.2 using `pip3 install --upgrade pip` [(see the documentation here)](https://pip.pypa.io/en/stable/installing/#upgrading-pip) and then try to `pip3 install pvacseq`

I created an ubuntu VM to test this all out.  I ran `sudo apt-get install python3.5 python3-pip` to get the packages, then `pip3 install --upgrade pip` to update to the newest version (although my pip3 was at 8.1.1 already, for some reason).  I then ran `pip3 install pvacseq` which gave me a permission error (which I've never seen before in pip) but `sudo pip3 install pvacseq` worked fine

**Comment by agraubert** [comment]
I tested that on ubuntu 16.04 (oops), but I'm making a new VM right now on 14.04 to test it again

**Comment by agraubert** [comment]
Okay, so that time I had to do the same fiddling around with repositories and symlinks as you did, but again, `sudo pip3 install pvacseq` did the trick.  On 14.04, I'm unable to update pip beyond 1.5.4, since it's owned by the OS (and attempts to force installation have found me without pip :disappointed:).  However, it seems with 14.04 the biggest issue was installing python3.5, which is beyond the scope of pvacseq.  We're updating our documentation now, but installation of python3.5 will still mostly be up to the user. 
On that note, if you're still having trouble with installing pvacseq itself, or running the commands (as you mentioned above), please let us know here, and we'd be happy to help you out.

**Comment by serge2016** [comment]
I have found the solution.
I have to run pip3 install --upgrade pip twice! It reports that it can't update pip but it does (on the second time)! After that pip3 install pvacseq works fine and errors disappear!

Please, provide such instruction. Let it be with dirty but working commands to install python3.5, upgrade pip3 and so on...

**Comment by susannasiebert** [comment]
@serge2016, I'm glad you were able to get your environment set up correctly. Unfortunately, providing detailed instructions on setting up your python environment is outside of the scope of the installation instructions for pvacseq. It will be up to the user to figure out how to set up their environment to meet requirements outlined in the installation instructions. We simply cannot cover all of the caveats and intricacies for all the different operating systems and versions that are out there. Instead, we have tried in our installation instructions to point to resources that might be helpful for setting up your environment. 

Are you now able to run pvacseq?

**Comment by serge2016** [comment]
@susannasiebert, Yes, thank you very much. I'll continue testing:)
Maybe it would be helpful to mention (select in bold) that python3.5 and pip3 (8.1.2) are required?

**Comment by susannasiebert** [comment]
We have updated the installation instructions to make it clear that python3.5 is required. We also added a sentence that `pip3` might need to be used instead of `pip` and we linked to instructions on how to install and upgrade pip.

I will resolve this issue at this point.
