### ISSUE TITLE
Using VEP

### ISSUE THREAD

**Issue by serge2016** [griffithlab/pVAC-Seq#81]
In the installation instructions there is a typo:
Example VEP Command
perl variant_effect_predictor.pl --input**-**file <input VCF> --format vcf --output_file <output VCF> --vcf --symbol --terms SO --plugin Downstream --plugin Wildtype [--dir_plugins <VEP_plugins directory>]
Correct option is --input**_**file.

--terms [ensembl|so] Default = "SO", so it is not necessary to specify.

What are the recommendations about  --cache --dir <path_to_cache>

VEP installation example:
perl INSTALL.pl -a ap -s homo_sapiens -y GRCh37 -g Downstream

**Comment by susannasiebert** [comment]
I updated the VEP example to fix the typo. Thanks for letting us know.

When we run VEP locally we use the `--cache` option. For the `--dir` option we just pick a unique temp directory. Otherwise VEP might overwrite some intermediate files if you do multiple VEP runs at the same time.

**Comment by susannasiebert** [comment]
@serge2016 Do you need anymore assistance with running VEP or can this issue be resolved?

**Comment by serge2016** [comment]
@susannasiebert Thank you! I didn't check it yet, but I think all is ok)
