### ISSUE TITLE
Typo in description

### ISSUE THREAD

**Issue by serge2016** [griffithlab/pVAC-Seq#83]
coverage_filter

pvacseq coverage_filters <input TSV file> <output file> [--normal-cov normal coverage cutoff] [--tdna-cov tumor DNA coverage cutoff] [--trna-cov tu**r**mor **D**NA coverage cutoff] [--normal-vaf normal vaf cutoff] [--tdna-vaf tumor DNA vaf cutoff] [--trna-vaf tumor RNA vaf cutoff] [--expn-val gene expression (fpkm) cutoff]
Correct: --trna-cov t**um**or **R**NA coverage cutoff

**Comment by susannasiebert** [comment]
This has been fixed. Resolving.
