### ISSUE TITLE
pVAC-Seq stdout

### ISSUE THREAD

**Issue by serge2016** [griffithlab/pVAC-Seq#84]
Is it possible to make pVAC-Seq not to print peptides with info to the screen? If I understand correct this is an output of netMHC..
`
Friday July  8 2016 18:24
NetMHC version 3.4. 8mer predictions using Artificial Neural Networks - Approx+Direct. Allele HLA-A02:01. 
Strong binder threshold  50 nM. Weak binder threshold score 500 nM

----------------------------------------------------------------------------------------------------
 pos    peptide      logscore affinity(nM) Bind Level    Protein Name     Allele
----------------------------------------------------------------------------------------------------
...
--------------------------------------------------------------------------------------------------
   0   CLAPPLPS         0.336         1322            MT.PLXNB3_ENST00000448847_1.missense.160P/S HLA-A02:01
   1   LAPPLPSE         0.046        30253            MT.PLXNB3_ENST00000448847_1.missense.160P/S HLA-A02:01
   2   APPLPSEQ         0.042        31796            MT.PLXNB3_ENST00000448847_1.missense.160P/S HLA-A02:01
   3   PPLPSEQD         0.039        32650            MT.PLXNB3_ENST00000448847_1.missense.160P/S HLA-A02:01
   4   PLPSEQDS         0.064        25028            MT.PLXNB3_ENST00000448847_1.missense.160P/S HLA-A02:01
   5   LPSEQDSP         0.046        30296            MT.PLXNB3_ENST00000448847_1.missense.160P/S HLA-A02:01
   6   PSEQDSPV         0.059        26430            MT.PLXNB3_ENST00000448847_1.missense.160P/S HLA-A02:01
   7   SEQDSPVN         0.042        31885            MT.PLXNB3_ENST00000448847_1.missense.160P/S HLA-A02:01
--------------------------------------------------------------------------------------------------

Converting VCF to TSV
Completed
Generating Variant Peptide FASTA File
Completed
Generating FASTA Key File
Completed
Running NetMHC on Allele HLA-A02:01 and Epitope Length 8
Completed
Parsing NetMHC Output
Completed
Running Binding Filters
Completed

Done: pvacseq has completed. File /output/pat126-realigned_old_filtered.tsv contains list of binding-filtered putative neoantigens
We recommend appending coverage information and running CoverageFilters.py to filter based on sequencing coverage information
`

**Comment by agraubert** [comment]
Thank you for pointing this out.  We've released a patch to pvacseq which resolves this issue. You can use `pip install pvacseq --upgrade` to update to the newest version
