### ISSUE TITLE
Add IEDB test.

### ISSUE THREAD

**Issue by jasonwalker80** [griffithlab/pVAC-Seq#98]
Add a test that IEDB is working and the output is as expected.  This is triggered by using mock data in the integration test, see #95.

**Comment by agraubert** [comment]
Should this test be part of the rest of test suite?  In my opinion, the whole advantage of using the mocked requests was that it kept the tests independent of external issues.  We've seen tests fail before simply because IEDB was down

**Comment by susannasiebert** [comment]
It should be outside of the integration tests. Something like a Jenkins test suite that runs a daily weather report to ensure that IEDB is up and that the output format on their end hasn't changed (i.e., when they release a new version). We'll have to figure out how to maybe have this be standalone without us having to set up a server or anything that relies on local IT infrastructure.

**Comment by jasonwalker80** [comment]
This could be useful:
https://nightli.es/
